//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itron.Metering.SharedControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolBoxChartResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolBoxChartResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itron.Metering.SharedControls.ToolBoxChartResources", typeof(ToolBoxChartResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;&lt;Chart2DPropBag Version=&quot;2.0.20073.17282&quot; UseAntiAliasedGraphics=&quot;True&quot; UseAntiAliasedText=&quot;True&quot;&gt;&lt;StyleCollection&gt;&lt;NamedStyle Name=&quot;Area&quot; ParentName=&quot;Area.default&quot; StyleData=&quot;BackColor2=127, 127, 127;Border=None,ControlDark,1;Opaque=False;GradientStyle=Radial;BackColor=White;Font=Microsoft Sans Serif, 9.75pt;HatchStyle=None;ForeColor=Black;Rounding=10 10 10 10;&quot; /&gt;&lt;NamedStyle Name=&quot;Style8&quot; ParentName=&quot;LabelStyleDefault&quot; StyleData=&quot;ForeColor=Black;Font=Microsoft Sans Serif, 11.25pt, sty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PowerCirclePropBag {
            get {
                return ResourceManager.GetString("PowerCirclePropBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;&lt;Chart2DPropBag Version=&quot;2.0.20073.17282&quot; UseAntiAliasedGraphics=&quot;True&quot; UseAntiAliasedText=&quot;True&quot;&gt;&lt;StyleCollection&gt;&lt;NamedStyle Name=&quot;Area&quot; ParentName=&quot;Area.default&quot; StyleData=&quot;GradientStyle=Radial;Border=None,Black,1;Font=Microsoft Sans Serif, 9.75pt;ForeColor=Black;BackColor=White;BackColor2=127, 127, 127;Opaque=False;Rounding=15 15 15 15;&quot; /&gt;&lt;NamedStyle Name=&quot;Style8&quot; ParentName=&quot;LabelStyleDefault&quot; StyleData=&quot;ForeColor=Black;Font=Microsoft Sans Serif, 11.25pt, style=Bold;&quot; /&gt;&lt;NamedStyl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ToolBoxChartPropBag {
            get {
                return ResourceManager.GetString("ToolBoxChartPropBag", resourceCulture);
            }
        }
    }
}
