//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itron.Metering.Datafiles.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itron.Metering.Datafiles.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Activated.
        /// </summary>
        internal static string ALARM_ACTIVATED {
            get {
                return ResourceManager.GetString("ALARM_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancillary Data.
        /// </summary>
        internal static string ANCILLARY_DATA {
            get {
                return ResourceManager.GetString("ANCILLARY_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic.
        /// </summary>
        internal static string Arithmetic {
            get {
                return ResourceManager.GetString("Arithmetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Timeset Performed.
        /// </summary>
        internal static string AUTO_TIMESET {
            get {
                return ResourceManager.GetString("AUTO_TIMESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Failure.
        /// </summary>
        internal static string BATT_FAIL {
            get {
                return ResourceManager.GetString("BATT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Reset.
        /// </summary>
        internal static string BILLING_RESET {
            get {
                return ResourceManager.GetString("BILLING_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string BlockDemandCalculation {
            get {
                return ResourceManager.GetString("BlockDemandCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capabilities Data.
        /// </summary>
        internal static string CAPABILITIES_DATA {
            get {
                return ResourceManager.GetString("CAPABILITIES_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Meter.
        /// </summary>
        internal static string CLIENT_METER {
            get {
                return ResourceManager.GetString("CLIENT_METER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock Enabled.
        /// </summary>
        internal static string CLOCK_ENABLED {
            get {
                return ResourceManager.GetString("CLOCK_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock Related Data.
        /// </summary>
        internal static string CLOCK_RELATED_DATA {
            get {
                return ResourceManager.GetString("CLOCK_RELATED_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string CMD {
            get {
                return ResourceManager.GetString("CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Response.
        /// </summary>
        internal static string CMD_RESPONSE {
            get {
                return ResourceManager.GetString("CMD_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Changed.
        /// </summary>
        internal static string CONFIG_CHANGED {
            get {
                return ResourceManager.GetString("CONFIG_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error.
        /// </summary>
        internal static string CONFIG_ERROR {
            get {
                return ResourceManager.GetString("CONFIG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants Data.
        /// </summary>
        internal static string CONSTANTS_DATA {
            get {
                return ResourceManager.GetString("CONSTANTS_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT Multiplier.
        /// </summary>
        internal static string CT_MULT {
            get {
                return ResourceManager.GetString("CT_MULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Battery Reading.
        /// </summary>
        internal static string CURRENT_BATT_READ {
            get {
                return ResourceManager.GetString("CURRENT_BATT_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Cumulative Demand Data.
        /// </summary>
        internal static string CURRENT_CUM_DEM_DATA {
            get {
                return ResourceManager.GetString("CURRENT_CUM_DEM_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Demand Data.
        /// </summary>
        internal static string CURRENT_DEM_DATA {
            get {
                return ResourceManager.GetString("CURRENT_DEM_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Demand Time of Occurrence Data.
        /// </summary>
        internal static string CURRENT_DEM_TOO_DATA {
            get {
                return ResourceManager.GetString("CURRENT_DEM_TOO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Energy Data.
        /// </summary>
        internal static string CURRENT_ENERGY_DATA {
            get {
                return ResourceManager.GetString("CURRENT_ENERGY_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Season Total.
        /// </summary>
        internal static string CURRENT_SEASON_TOTAL {
            get {
                return ResourceManager.GetString("CURRENT_SEASON_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current State Data.
        /// </summary>
        internal static string CURRENT_STATE_DATA {
            get {
                return ResourceManager.GetString("CURRENT_STATE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Time.
        /// </summary>
        internal static string CURRENT_TIME {
            get {
                return ResourceManager.GetString("CURRENT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer 1 Alarm.
        /// </summary>
        internal static string CUST_1_ALARM {
            get {
                return ResourceManager.GetString("CUST_1_ALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer 1 Alarm Off.
        /// </summary>
        internal static string CUST_1_ALARM_OFF {
            get {
                return ResourceManager.GetString("CUST_1_ALARM_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer 2 Alarm.
        /// </summary>
        internal static string CUST_2_ALARM {
            get {
                return ResourceManager.GetString("CUST_2_ALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        internal static string CUSTOMER_ID {
            get {
                return ResourceManager.GetString("CUSTOMER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Freeze Reading.
        /// </summary>
        internal static string DAILY_FREEZE_READING {
            get {
                return ResourceManager.GetString("DAILY_FREEZE_READING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Flash.
        /// </summary>
        internal static string DATA_FLASH {
            get {
                return ResourceManager.GetString("DATA_FLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data RAM Error Detected.
        /// </summary>
        internal static string DATA_RAM_ERR {
            get {
                return ResourceManager.GetString("DATA_RAM_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days on Battery.
        /// </summary>
        internal static string DAYS_ON_BATT {
            get {
                return ResourceManager.GetString("DAYS_ON_BATT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Since Last Demand Reset.
        /// </summary>
        internal static string DAYS_SINCE_LAST_DR {
            get {
                return ResourceManager.GetString("DAYS_SINCE_LAST_DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Since Last Test.
        /// </summary>
        internal static string DAYS_SINCE_LAST_TEST {
            get {
                return ResourceManager.GetString("DAYS_SINCE_LAST_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Interval Length.
        /// </summary>
        internal static string DEM_INT_LEN {
            get {
                return ResourceManager.GetString("DEM_INT_LEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Reset.
        /// </summary>
        internal static string DEM_RESET {
            get {
                return ResourceManager.GetString("DEM_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Reset Count.
        /// </summary>
        internal static string DEM_RESET_COUNT {
            get {
                return ResourceManager.GetString("DEM_RESET_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Threshold Caution.
        /// </summary>
        internal static string DEM_THRESH_CAUTION {
            get {
                return ResourceManager.GetString("DEM_THRESH_CAUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Threshold Condition Cleared.
        /// </summary>
        internal static string DEM_THRESH_COND_CLEARED {
            get {
                return ResourceManager.GetString("DEM_THRESH_COND_CLEARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Threshold Exceeded.
        /// </summary>
        internal static string DEM_THRESHOLD_EXCEEDED {
            get {
                return ResourceManager.GetString("DEM_THRESHOLD_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic 1 Active.
        /// </summary>
        internal static string DIAG_1_ACTIVE {
            get {
                return ResourceManager.GetString("DIAG_1_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic 1 Inactive.
        /// </summary>
        internal static string DIAG_1_INACTIVE {
            get {
                return ResourceManager.GetString("DIAG_1_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic 2 Active.
        /// </summary>
        internal static string DIAG_2_ACTIVE {
            get {
                return ResourceManager.GetString("DIAG_2_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic 2 Inactive.
        /// </summary>
        internal static string DIAG_2_INACTIVE {
            get {
                return ResourceManager.GetString("DIAG_2_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic 3 Active.
        /// </summary>
        internal static string DIAG_3_ACTIVE {
            get {
                return ResourceManager.GetString("DIAG_3_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic 3 Inactive.
        /// </summary>
        internal static string DIAG_3_INACTIVE {
            get {
                return ResourceManager.GetString("DIAG_3_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic 4 Active.
        /// </summary>
        internal static string DIAG_4_ACTIVE {
            get {
                return ResourceManager.GetString("DIAG_4_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic 4 Inactive.
        /// </summary>
        internal static string DIAG_4_INACTIVE {
            get {
                return ResourceManager.GetString("DIAG_4_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic 5 Active.
        /// </summary>
        internal static string DIAG_5_ACTIVE {
            get {
                return ResourceManager.GetString("DIAG_5_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic 5 Inactive.
        /// </summary>
        internal static string DIAG_5_INACTIVE {
            get {
                return ResourceManager.GetString("DIAG_5_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic 6 Active.
        /// </summary>
        internal static string DIAG_6_ACTIVE {
            get {
                return ResourceManager.GetString("DIAG_6_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic 6 Inactive.
        /// </summary>
        internal static string DIAG_6_INACTIVE {
            get {
                return ResourceManager.GetString("DIAG_6_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic Failure.
        /// </summary>
        internal static string DIAG_FAIL {
            get {
                return ResourceManager.GetString("DIAG_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DST Change – New Time.
        /// </summary>
        internal static string DST_CHANGE_NEW {
            get {
                return ResourceManager.GetString("DST_CHANGE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DST Enabled.
        /// </summary>
        internal static string DST_ENABLED {
            get {
                return ResourceManager.GetString("DST_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEPROM Failure.
        /// </summary>
        internal static string EEPROM_FAIL {
            get {
                return ResourceManager.GetString("EEPROM_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Of Calendar Warning.
        /// </summary>
        internal static string END_OF_CAL_WARN {
            get {
                return ResourceManager.GetString("END_OF_CAL_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Test Mode.
        /// </summary>
        internal static string END_TEST_MODE {
            get {
                return ResourceManager.GetString("END_TEST_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Itron Security.
        /// </summary>
        internal static string EnhancedItronSecurity {
            get {
                return ResourceManager.GetString("EnhancedItronSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Power Fail Count.
        /// </summary>
        internal static string EPF_COUNT {
            get {
                return ResourceManager.GetString("EPF_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Power Fail Data.
        /// </summary>
        internal static string EPF_DATA {
            get {
                return ResourceManager.GetString("EPF_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string EVENT {
            get {
                return ResourceManager.GetString("EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Data.
        /// </summary>
        internal static string EVENT_DATA {
            get {
                return ResourceManager.GetString("EVENT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Log Reset.
        /// </summary>
        internal static string EVENT_LOG_RESET {
            get {
                return ResourceManager.GetString("EVENT_LOG_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall DST Change.
        /// </summary>
        internal static string FALL_DST_CHANGE {
            get {
                return ResourceManager.GetString("FALL_DST_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error #1 - Processor Flash Error.
        /// </summary>
        internal static string FATAL_1 {
            get {
                return ResourceManager.GetString("FATAL_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error #2 - Processor RAM Error.
        /// </summary>
        internal static string FATAL_2 {
            get {
                return ResourceManager.GetString("FATAL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error #3 - Data Flash Error.
        /// </summary>
        internal static string FATAL_3 {
            get {
                return ResourceManager.GetString("FATAL_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error #4 - Metrology Communications Error.
        /// </summary>
        internal static string FATAL_4 {
            get {
                return ResourceManager.GetString("FATAL_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error #5 - Power Down Error.
        /// </summary>
        internal static string FATAL_5 {
            get {
                return ResourceManager.GetString("FATAL_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error #6 - File System Error.
        /// </summary>
        internal static string FATAL_6 {
            get {
                return ResourceManager.GetString("FATAL_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error #7 - Operating System Error.
        /// </summary>
        internal static string FATAL_7 {
            get {
                return ResourceManager.GetString("FATAL_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string FATAL_ERR {
            get {
                return ResourceManager.GetString("FATAL_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Errors.
        /// </summary>
        internal static string FATAL_ERRS {
            get {
                return ResourceManager.GetString("FATAL_ERRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Does Not Exist.
        /// </summary>
        internal static string FILE_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("FILE_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System.
        /// </summary>
        internal static string FILE_SYS {
            get {
                return ResourceManager.GetString("FILE_SYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Meter Readings.
        /// </summary>
        internal static string FREEZE_METER_READINGS {
            get {
                return ResourceManager.GetString("FREEZE_METER_READINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Version.
        /// </summary>
        internal static string FW_VERSION {
            get {
                return ResourceManager.GetString("FW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Battery Reading.
        /// </summary>
        internal static string GOOD_BATT_READ {
            get {
                return ResourceManager.GetString("GOOD_BATT_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAN Client Data.
        /// </summary>
        internal static string HAN_CLIENT_DATA {
            get {
                return ResourceManager.GetString("HAN_CLIENT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical.
        /// </summary>
        internal static string HISTORICAL {
            get {
                return ResourceManager.GetString("HISTORICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input High.
        /// </summary>
        internal static string INPUT_HIGH {
            get {
                return ResourceManager.GetString("INPUT_HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Low.
        /// </summary>
        internal static string INPUT_LOW {
            get {
                return ResourceManager.GetString("INPUT_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent Register Communications Failure.
        /// </summary>
        internal static string INTELLIGENT_REG_COMM_FAIL {
            get {
                return ResourceManager.GetString("INTELLIGENT_REG_COMM_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent Register Communications Restored.
        /// </summary>
        internal static string INTELLIGENT_REG_COMM_RESTORED {
            get {
                return ResourceManager.GetString("INTELLIGENT_REG_COMM_RESTORED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Option Board Event.
        /// </summary>
        internal static string INTERNAL_OP_BOARD_EVENT {
            get {
                return ResourceManager.GetString("INTERNAL_OP_BOARD_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval Data.
        /// </summary>
        internal static string INTERVAL_DATA {
            get {
                return ResourceManager.GetString("INTERVAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string ITEM {
            get {
                return ResourceManager.GetString("ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lag.
        /// </summary>
        internal static string Lag {
            get {
                return ResourceManager.GetString("Lag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Billing Period Cumulative Demand Data.
        /// </summary>
        internal static string LAST_BP_CUM_DEM_DATA {
            get {
                return ResourceManager.GetString("LAST_BP_CUM_DEM_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Billing Period Demand Data.
        /// </summary>
        internal static string LAST_BP_DEM_DATA {
            get {
                return ResourceManager.GetString("LAST_BP_DEM_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Billing Period Demand Time of Occurrence Data.
        /// </summary>
        internal static string LAST_BP_DEM_TOO_DATA {
            get {
                return ResourceManager.GetString("LAST_BP_DEM_TOO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Billing Period Energy Data.
        /// </summary>
        internal static string LAST_BP_ENERGY_DATA {
            get {
                return ResourceManager.GetString("LAST_BP_ENERGY_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Billing Period State Data.
        /// </summary>
        internal static string LAST_BP_STATE_DATA {
            get {
                return ResourceManager.GetString("LAST_BP_STATE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Billing Period Time.
        /// </summary>
        internal static string LAST_BP_TIME {
            get {
                return ResourceManager.GetString("LAST_BP_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Self Read Cumulative Demand Data.
        /// </summary>
        internal static string LAST_SR_CUM_DEM_DATA {
            get {
                return ResourceManager.GetString("LAST_SR_CUM_DEM_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Self Read Demand Data.
        /// </summary>
        internal static string LAST_SR_DEM_DATA {
            get {
                return ResourceManager.GetString("LAST_SR_DEM_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Self Read Demand Time of Occurrence Data.
        /// </summary>
        internal static string LAST_SR_DEM_TOO_DATA {
            get {
                return ResourceManager.GetString("LAST_SR_DEM_TOO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Self Read Energy Data.
        /// </summary>
        internal static string LAST_SR_ENERGY_DATA {
            get {
                return ResourceManager.GetString("LAST_SR_ENERGY_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Self Read State Data.
        /// </summary>
        internal static string LAST_SR_STATE_DATA {
            get {
                return ResourceManager.GetString("LAST_SR_STATE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Self Read Time.
        /// </summary>
        internal static string LAST_SR_TIME {
            get {
                return ResourceManager.GetString("LAST_SR_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Reading.
        /// </summary>
        internal static string LATEST_READING {
            get {
                return ResourceManager.GetString("LATEST_READING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Battery.
        /// </summary>
        internal static string LOW_BATT {
            get {
                return ResourceManager.GetString("LOW_BATT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Profile Data Corrupted.
        /// </summary>
        internal static string LP_DATA_CORRUPT {
            get {
                return ResourceManager.GetString("LP_DATA_CORRUPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Memory.
        /// </summary>
        internal static string MASS_MEMORY {
            get {
                return ResourceManager.GetString("MASS_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCU Flash.
        /// </summary>
        internal static string MCU_FLASH {
            get {
                return ResourceManager.GetString("MCU_FLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Address.
        /// </summary>
        internal static string METER_ADDRESS {
            get {
                return ResourceManager.GetString("METER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Over Threshold.
        /// </summary>
        internal static string METER_OVER_THRESH {
            get {
                return ResourceManager.GetString("METER_OVER_THRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Type.
        /// </summary>
        internal static string METER_TYPE {
            get {
                return ResourceManager.GetString("METER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrology Communications.
        /// </summary>
        internal static string METROLOGY_COMMS {
            get {
                return ResourceManager.GetString("METROLOGY_COMMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string MINUTES {
            get {
                return ResourceManager.GetString("MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Fatal Error.
        /// </summary>
        internal static string NON_FATAL_ERR {
            get {
                return ResourceManager.GetString("NON_FATAL_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Fatal Errors.
        /// </summary>
        internal static string NON_FATAL_ERRS {
            get {
                return ResourceManager.GetString("NON_FATAL_ERRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Cumulative Demands.
        /// </summary>
        internal static string NUM_OF_CUM_DEMANDS {
            get {
                return ResourceManager.GetString("NUM_OF_CUM_DEMANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Demands.
        /// </summary>
        internal static string NUM_OF_DEMANDS {
            get {
                return ResourceManager.GetString("NUM_OF_DEMANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Energies.
        /// </summary>
        internal static string NUM_OF_ENERGIES {
            get {
                return ResourceManager.GetString("NUM_OF_ENERGIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Load Profile Channels.
        /// </summary>
        internal static string NUM_OF_LP_CHANNELS {
            get {
                return ResourceManager.GetString("NUM_OF_LP_CHANNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating Parameter changed.
        /// </summary>
        internal static string OP_PARAM_CHANGED {
            get {
                return ResourceManager.GetString("OP_PARAM_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        internal static string OP_SYS {
            get {
                return ResourceManager.GetString("OP_SYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Outage Count.
        /// </summary>
        internal static string OUTAGE_COUNT {
            get {
                return ResourceManager.GetString("OUTAGE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PF Average Billing Period Available.
        /// </summary>
        internal static string PF_AVG_BILL_PERIOD_AVAILABLE {
            get {
                return ResourceManager.GetString("PF_AVG_BILL_PERIOD_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Drop-out (Phase, short/long).
        /// </summary>
        internal static string PHASE_DROPOUT {
            get {
                return ResourceManager.GetString("PHASE_DROPOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Failure.
        /// </summary>
        internal static string PHASE_FAIL {
            get {
                return ResourceManager.GetString("PHASE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Loss.
        /// </summary>
        internal static string PHASE_LOSS {
            get {
                return ResourceManager.GetString("PHASE_LOSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Restoration.
        /// </summary>
        internal static string PHASE_RESTORATION {
            get {
                return ResourceManager.GetString("PHASE_RESTORATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Voltages &lt; 80% of Voltage Class.
        /// </summary>
        internal static string PHASE_VOLT_LESS_80 {
            get {
                return ResourceManager.GetString("PHASE_VOLT_LESS_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC Power Down.
        /// </summary>
        internal static string POWER_DOWN {
            get {
                return ResourceManager.GetString("POWER_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC Power Up.
        /// </summary>
        internal static string POWER_UP {
            get {
                return ResourceManager.GetString("POWER_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program ID.
        /// </summary>
        internal static string PROG_ID {
            get {
                return ResourceManager.GetString("PROG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times Programmed Count.
        /// </summary>
        internal static string PROGRAM_COUNT {
            get {
                return ResourceManager.GetString("PROGRAM_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Overflow.
        /// </summary>
        internal static string PULSE_OVERFLOW {
            get {
                return ResourceManager.GetString("PULSE_OVERFLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Identification.
        /// </summary>
        internal static string QUANT_IDENTIFICATION {
            get {
                return ResourceManager.GetString("QUANT_IDENTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        internal static string RAM {
            get {
                return ResourceManager.GetString("RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM Error Detected.
        /// </summary>
        internal static string RAM_ERR {
            get {
                return ResourceManager.GetString("RAM_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Change.
        /// </summary>
        internal static string RATE_CHANGE {
            get {
                return ResourceManager.GetString("RATE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate ID.
        /// </summary>
        internal static string RATE_ID {
            get {
                return ResourceManager.GetString("RATE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate A.
        /// </summary>
        internal static string RATEA {
            get {
                return ResourceManager.GetString("RATEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate B.
        /// </summary>
        internal static string RATEB {
            get {
                return ResourceManager.GetString("RATEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate C.
        /// </summary>
        internal static string RATEC {
            get {
                return ResourceManager.GetString("RATEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate D.
        /// </summary>
        internal static string RATED {
            get {
                return ResourceManager.GetString("RATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Time.
        /// </summary>
        internal static string READING_TIME {
            get {
                return ResourceManager.GetString("READING_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder Clock Malfunction Detected.
        /// </summary>
        internal static string RECORDER_CLOCK_MALFUNCTION {
            get {
                return ResourceManager.GetString("RECORDER_CLOCK_MALFUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder Clock Set – New Time.
        /// </summary>
        internal static string RECORDER_CLOCK_SET_NEW {
            get {
                return ResourceManager.GetString("RECORDER_CLOCK_SET_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Full-scale Exceeded.
        /// </summary>
        internal static string REG_FULL_SCALE_EXCEEDED {
            get {
                return ResourceManager.GetString("REG_FULL_SCALE_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous kW &gt; Register Full-Scale Value.
        /// </summary>
        internal static string REG_FULLSCALE_EXCEEDED_EVENT {
            get {
                return ResourceManager.GetString("REG_FULLSCALE_EXCEEDED_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Multiplier.
        /// </summary>
        internal static string REG_MULT {
            get {
                return ResourceManager.GetString("REG_MULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Data.
        /// </summary>
        internal static string REGISTER_DATA {
            get {
                return ResourceManager.GetString("REGISTER_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string RESPONSE {
            get {
                return ResourceManager.GetString("RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Power Flow.
        /// </summary>
        internal static string REV_POWER_FLOW {
            get {
                return ResourceManager.GetString("REV_POWER_FLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Running Ceased.
        /// </summary>
        internal static string REV_RUNNING_CEASED {
            get {
                return ResourceManager.GetString("REV_RUNNING_CEASED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Running Detected.
        /// </summary>
        internal static string REV_RUNNING_DETECTED {
            get {
                return ResourceManager.GetString("REV_RUNNING_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse engineered from .
        /// </summary>
        internal static string REVERSE_ENGINEERED_FROM {
            get {
                return ResourceManager.GetString("REVERSE_ENGINEERED_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Call-in.
        /// </summary>
        internal static string SCHED_CALLIN {
            get {
                return ResourceManager.GetString("SCHED_CALLIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season Change.
        /// </summary>
        internal static string SEASON_CHANGE {
            get {
                return ResourceManager.GetString("SEASON_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Read.
        /// </summary>
        internal static string SELF_READ {
            get {
                return ResourceManager.GetString("SELF_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Read Data Available.
        /// </summary>
        internal static string SELF_READ_AVAILABLE {
            get {
                return ResourceManager.GetString("SELF_READ_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliding.
        /// </summary>
        internal static string SlidingDemandCalculation {
            get {
                return ResourceManager.GetString("SlidingDemandCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Validation.
        /// </summary>
        internal static string SOURCE_VALIDATION {
            get {
                return ResourceManager.GetString("SOURCE_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring DST Change.
        /// </summary>
        internal static string SPRING_DST_CHANGE {
            get {
                return ResourceManager.GetString("SPRING_DST_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard C12.22 Security.
        /// </summary>
        internal static string StandardC1222Security {
            get {
                return ResourceManager.GetString("StandardC1222Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of Test Mode.
        /// </summary>
        internal static string START_TEST_MODE {
            get {
                return ResourceManager.GetString("START_TEST_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Codes.
        /// </summary>
        internal static string STATUS_CODES {
            get {
                return ResourceManager.GetString("STATUS_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Input Closing.
        /// </summary>
        internal static string STATUS_INPUT_CLOSING {
            get {
                return ResourceManager.GetString("STATUS_INPUT_CLOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Input Opening.
        /// </summary>
        internal static string STATUS_INPUT_OPENING {
            get {
                return ResourceManager.GetString("STATUS_INPUT_OPENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Client Data Size.
        /// </summary>
        internal static string SUPPORTED_CLIENT_DATA_SIZE {
            get {
                return ResourceManager.GetString("SUPPORTED_CLIENT_DATA_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Number of Clients.
        /// </summary>
        internal static string SUPPORTED_NUM_CLIENTS {
            get {
                return ResourceManager.GetString("SUPPORTED_NUM_CLIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of Contents.
        /// </summary>
        internal static string TABLE_OF_CONTENTS {
            get {
                return ResourceManager.GetString("TABLE_OF_CONTENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamper Indication.
        /// </summary>
        internal static string TAMPER_INDICATION {
            get {
                return ResourceManager.GetString("TAMPER_INDICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Mode Data.
        /// </summary>
        internal static string TEST_MODE_DATA {
            get {
                return ResourceManager.GetString("TEST_MODE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time or Date Changed.
        /// </summary>
        internal static string TIME_DATE_CHANGED {
            get {
                return ResourceManager.GetString("TIME_DATE_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of Last Interrogation.
        /// </summary>
        internal static string TIME_LAST_INTERROGATION {
            get {
                return ResourceManager.GetString("TIME_LAST_INTERROGATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of Last Outage.
        /// </summary>
        internal static string TIME_LAST_OUTAGE {
            get {
                return ResourceManager.GetString("TIME_LAST_OUTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top of page.
        /// </summary>
        internal static string TOP_OF_PAGE {
            get {
                return ResourceManager.GetString("TOP_OF_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOU Rates.
        /// </summary>
        internal static string TOU_RATES {
            get {
                return ResourceManager.GetString("TOU_RATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOU Schedule.
        /// </summary>
        internal static string TOU_SCHED {
            get {
                return ResourceManager.GetString("TOU_SCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOU Schedule Error.
        /// </summary>
        internal static string TOU_SCHED_ERR {
            get {
                return ResourceManager.GetString("TOU_SCHED_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Accessed.
        /// </summary>
        internal static string UNIT_ACCESSED {
            get {
                return ResourceManager.GetString("UNIT_ACCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Accessed with Invalid Password.
        /// </summary>
        internal static string UNIT_ACCESSED_INVALID_PW {
            get {
                return ResourceManager.GetString("UNIT_ACCESSED_INVALID_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Accessed by Reader.
        /// </summary>
        internal static string UNIT_ACCESSED_READER {
            get {
                return ResourceManager.GetString("UNIT_ACCESSED_READER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Accessed Remotely.
        /// </summary>
        internal static string UNIT_ACCESSED_REMOTE {
            get {
                return ResourceManager.GetString("UNIT_ACCESSED_REMOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Recorder Event.
        /// </summary>
        internal static string UNRECOGNIZED_RECORDER_EVENT {
            get {
                return ResourceManager.GetString("UNRECOGNIZED_RECORDER_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string VALUE {
            get {
                return ResourceManager.GetString("VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vectorial.
        /// </summary>
        internal static string Vectorial {
            get {
                return ResourceManager.GetString("Vectorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage Cut.
        /// </summary>
        internal static string VOLT_CUT {
            get {
                return ResourceManager.GetString("VOLT_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage Imbalance.
        /// </summary>
        internal static string VOLT_IMBALANCE {
            get {
                return ResourceManager.GetString("VOLT_IMBALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage Sag.
        /// </summary>
        internal static string VOLT_SAG {
            get {
                return ResourceManager.GetString("VOLT_SAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage Swell.
        /// </summary>
        internal static string VOLT_SWELL {
            get {
                return ResourceManager.GetString("VOLT_SWELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VQ Log Near Full.
        /// </summary>
        internal static string VQ_LOG_NEAR_FULL {
            get {
                return ResourceManager.GetString("VQ_LOG_NEAR_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VT Multiplier.
        /// </summary>
        internal static string VT_MULT {
            get {
                return ResourceManager.GetString("VT_MULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchdog Timeout.
        /// </summary>
        internal static string WATCHDOG_TIMEOUT {
            get {
                return ResourceManager.GetString("WATCHDOG_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Interval Value.
        /// </summary>
        internal static string ZERO_INT_VAL {
            get {
                return ResourceManager.GetString("ZERO_INT_VAL", resourceCulture);
            }
        }
    }
}
