//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itron.Metering.Device.DLMSDevice {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class COSEMResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal COSEMResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itron.Metering.Device.DLMSDevice.COSEMResourceStrings", typeof(COSEMResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Firmware Version.
        /// </summary>
        internal static string ActiveFirmwareVersion {
            get {
                return ResourceManager.GetString("ActiveFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Descriptor 1.
        /// </summary>
        internal static string AlarmDescriptor1 {
            get {
                return ResourceManager.GetString("AlarmDescriptor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Descriptor 2.
        /// </summary>
        internal static string AlarmDescriptor2 {
            get {
                return ResourceManager.GetString("AlarmDescriptor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Filter 1.
        /// </summary>
        internal static string AlarmFilter1 {
            get {
                return ResourceManager.GetString("AlarmFilter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Filter 2.
        /// </summary>
        internal static string AlarmFilter2 {
            get {
                return ResourceManager.GetString("AlarmFilter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Monitor 1.
        /// </summary>
        internal static string AlarmMonitor1 {
            get {
                return ResourceManager.GetString("AlarmMonitor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Push Setup.
        /// </summary>
        internal static string AlarmPushSetup {
            get {
                return ResourceManager.GetString("AlarmPushSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Register 1.
        /// </summary>
        internal static string AlarmRegister1 {
            get {
                return ResourceManager.GetString("AlarmRegister1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Register 2.
        /// </summary>
        internal static string AlarmRegister2 {
            get {
                return ResourceManager.GetString("AlarmRegister2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Registers Profile.
        /// </summary>
        internal static string AlarmRegistersProfile {
            get {
                return ResourceManager.GetString("AlarmRegistersProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Scripts.
        /// </summary>
        internal static string AlarmScripts {
            get {
                return ResourceManager.GetString("AlarmScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Disconnects, Remote Connect, No Local Connect.
        /// </summary>
        internal static string AllDisconnectsRemoteReconnectManualReconnectNoLocalReconnect {
            get {
                return ResourceManager.GetString("AllDisconnectsRemoteReconnectManualReconnectNoLocalReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Disconnects, Remote Connect to Ready, No Local Connect.
        /// </summary>
        internal static string AllDisconnectsRemoteReconnectsToReadyManualReconnectNoLocalReconnect {
            get {
                return ResourceManager.GetString("AllDisconnectsRemoteReconnectsToReadyManualReconnectNoLocalReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Disconnects, Remote Connect to Ready, Local Connect.
        /// </summary>
        internal static string AllDisconnectsRemoteReconnectToReadyManualReconnectLocalReconnect {
            get {
                return ResourceManager.GetString("AllDisconnectsRemoteReconnectToReadyManualReconnectLocalReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string Amp {
            get {
                return ResourceManager.GetString("Amp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Current (All Phases).
        /// </summary>
        internal static string AverageCurrentAllPhases {
            get {
                return ResourceManager.GetString("AverageCurrentAllPhases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Current (Phase A).
        /// </summary>
        internal static string AverageCurrentPhaseA {
            get {
                return ResourceManager.GetString("AverageCurrentPhaseA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Current (Phase B).
        /// </summary>
        internal static string AverageCurrentPhaseB {
            get {
                return ResourceManager.GetString("AverageCurrentPhaseB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Current (Phase C).
        /// </summary>
        internal static string AverageCurrentPhaseC {
            get {
                return ResourceManager.GetString("AverageCurrentPhaseC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Power Factor.
        /// </summary>
        internal static string AveragePF {
            get {
                return ResourceManager.GetString("AveragePF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Voltage (Phase A).
        /// </summary>
        internal static string AverageVoltagePhaseA {
            get {
                return ResourceManager.GetString("AverageVoltagePhaseA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Voltage (Phase B).
        /// </summary>
        internal static string AverageVoltagePhaseB {
            get {
                return ResourceManager.GetString("AverageVoltagePhaseB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Voltage (Phase C).
        /// </summary>
        internal static string AverageVoltagePhaseC {
            get {
                return ResourceManager.GetString("AverageVoltagePhaseC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bar.
        /// </summary>
        internal static string bar {
            get {
                return ResourceManager.GetString("bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Confirmation of Setting Values.
        /// </summary>
        internal static string BatchConfirmationOfSettingValues {
            get {
                return ResourceManager.GetString("BatchConfirmationOfSettingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Daily Self Read Data.
        /// </summary>
        internal static string BillingDailySelfReadData {
            get {
                return ResourceManager.GetString("BillingDailySelfReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Period 1 Data.
        /// </summary>
        internal static string BillingPeriod1Data {
            get {
                return ResourceManager.GetString("BillingPeriod1Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Self Read Data.
        /// </summary>
        internal static string BillingSelfReadData {
            get {
                return ResourceManager.GetString("BillingSelfReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot Count Unlock.
        /// </summary>
        internal static string BootCountUnlock {
            get {
                return ResourceManager.GetString("BootCountUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        internal static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        internal static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm Modeul Firmware Version.
        /// </summary>
        internal static string CommModuleFirmwareVersion {
            get {
                return ResourceManager.GetString("CommModuleFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Device Client Association.
        /// </summary>
        internal static string CommunicationDeviceAssociation {
            get {
                return ResourceManager.GetString("CommunicationDeviceAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Scripts.
        /// </summary>
        internal static string ConfigurationScripts {
            get {
                return ResourceManager.GetString("ConfigurationScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Tag.
        /// </summary>
        internal static string ConfigurationTag {
            get {
                return ResourceManager.GetString("ConfigurationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration XML.
        /// </summary>
        internal static string ConfigurationXML {
            get {
                return ResourceManager.GetString("ConfigurationXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COSEM Logical Device Name.
        /// </summary>
        internal static string COSEMLogicalDeviceName {
            get {
                return ResourceManager.GetString("COSEMLogicalDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string Coulomb {
            get {
                return ResourceManager.GetString("Coulomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Transformer Ratio (denominator).
        /// </summary>
        internal static string CTRatioDenominator {
            get {
                return ResourceManager.GetString("CTRatioDenominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Transformer Ratio (numerator).
        /// </summary>
        internal static string CTRatioNumerator {
            get {
                return ResourceManager.GetString("CTRatioNumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m^3.
        /// </summary>
        internal static string CubicMeter {
            get {
                return ResourceManager.GetString("CubicMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m^3/d.
        /// </summary>
        internal static string CubicMeterPerDay {
            get {
                return ResourceManager.GetString("CubicMeterPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m^3/h.
        /// </summary>
        internal static string CubicMeterPerHour {
            get {
                return ResourceManager.GetString("CubicMeterPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Association.
        /// </summary>
        internal static string CurrentAssociation {
            get {
                return ResourceManager.GetString("CurrentAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Date.
        /// </summary>
        internal static string CurrentDate {
            get {
                return ResourceManager.GetString("CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Time.
        /// </summary>
        internal static string CurrentTime {
            get {
                return ResourceManager.GetString("CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Value Confirmation.
        /// </summary>
        internal static string CurrentValueConfirmation {
            get {
                return ResourceManager.GetString("CurrentValueConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daylight Savings Schedule.
        /// </summary>
        internal static string DaylightSavingsSchedule {
            get {
                return ResourceManager.GetString("DaylightSavingsSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dbud Command Execute.
        /// </summary>
        internal static string DbusCommandExecute {
            get {
                return ResourceManager.GetString("DbusCommandExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        internal static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deregister Push Setup.
        /// </summary>
        internal static string DeregisterPushSetup {
            get {
                return ResourceManager.GetString("DeregisterPushSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID 1.
        /// </summary>
        internal static string DeviceID1 {
            get {
                return ResourceManager.GetString("DeviceID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID 2.
        /// </summary>
        internal static string DeviceID2 {
            get {
                return ResourceManager.GetString("DeviceID2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID 3.
        /// </summary>
        internal static string DeviceID3 {
            get {
                return ResourceManager.GetString("DeviceID3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID 4.
        /// </summary>
        internal static string DeviceID4 {
            get {
                return ResourceManager.GetString("DeviceID4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID 5.
        /// </summary>
        internal static string DeviceID5 {
            get {
                return ResourceManager.GetString("DeviceID5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiffGram EXI.
        /// </summary>
        internal static string DiffGramEXI {
            get {
                return ResourceManager.GetString("DiffGramEXI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiffGram XML.
        /// </summary>
        internal static string DiffGramXML {
            get {
                return ResourceManager.GetString("DiffGramXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable/Enable Other Displays.
        /// </summary>
        internal static string DisableOtherDisplays {
            get {
                return ResourceManager.GetString("DisableOtherDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Control.
        /// </summary>
        internal static string DisconnectControl {
            get {
                return ResourceManager.GetString("DisconnectControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Time (Delivered).
        /// </summary>
        internal static string DisplayTimeDelivered {
            get {
                return ResourceManager.GetString("DisplayTimeDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Time (Received).
        /// </summary>
        internal static string DisplayTimeReceived {
            get {
                return ResourceManager.GetString("DisplayTimeReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable Event Recording.
        /// </summary>
        internal static string EnableEventRecording {
            get {
                return ResourceManager.GetString("EnableEventRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable Screen Flicker.
        /// </summary>
        internal static string EnableScreenFlicker {
            get {
                return ResourceManager.GetString("EnableScreenFlicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energization Start Time Setting.
        /// </summary>
        internal static string EnergizationStartTime {
            get {
                return ResourceManager.GetString("EnergizationStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energization Start Time Confirmation.
        /// </summary>
        internal static string EnergizationStartTimeConfirmation {
            get {
                return ResourceManager.GetString("EnergizationStartTimeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Code.
        /// </summary>
        internal static string EventCode {
            get {
                return ResourceManager.GetString("EventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Data.
        /// </summary>
        internal static string EventData {
            get {
                return ResourceManager.GetString("EventData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Data Record Number.
        /// </summary>
        internal static string EventDataRecordNumber {
            get {
                return ResourceManager.GetString("EventDataRecordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string Farad {
            get {
                return ResourceManager.GetString("Farad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Load Script Table.
        /// </summary>
        internal static string FirmwareLoadScriptTable {
            get {
                return ResourceManager.GetString("FirmwareLoadScriptTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Load Action Schedule.
        /// </summary>
        internal static string FirmwareLoadSingleActionSchedule {
            get {
                return ResourceManager.GetString("FirmwareLoadSingleActionSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flicker Flag.
        /// </summary>
        internal static string FlickerFlag {
            get {
                return ResourceManager.GetString("FlickerFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full EXI.
        /// </summary>
        internal static string FullEXI {
            get {
                return ResourceManager.GetString("FullEXI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full XML.
        /// </summary>
        internal static string FullXML {
            get {
                return ResourceManager.GetString("FullXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Meter Reset Scripts.
        /// </summary>
        internal static string GlobalMeterResetScripts {
            get {
                return ResourceManager.GetString("GlobalMeterResetScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDLC Settings.
        /// </summary>
        internal static string HLDCSettings {
            get {
                return ResourceManager.GetString("HLDCSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HT Client Association.
        /// </summary>
        internal static string HTClientAssociation {
            get {
                return ResourceManager.GetString("HTClientAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Firmware Version (string).
        /// </summary>
        internal static string HumanReadableFirmwareVersion {
            get {
                return ResourceManager.GetString("HumanReadableFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Activation Complete Scripts.
        /// </summary>
        internal static string ImageActivationCompleteScripts {
            get {
                return ResourceManager.GetString("ImageActivationCompleteScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Activation Monitor.
        /// </summary>
        internal static string ImageActivationMonitor {
            get {
                return ResourceManager.GetString("ImageActivationMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Activation Push Setup.
        /// </summary>
        internal static string ImageActivationPushSetup {
            get {
                return ResourceManager.GetString("ImageActivationPushSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Process Status.
        /// </summary>
        internal static string ImageProcessStatus {
            get {
                return ResourceManager.GetString("ImageProcessStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Transfer.
        /// </summary>
        internal static string ImageTransfer {
            get {
                return ResourceManager.GetString("ImageTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImProv Status.
        /// </summary>
        internal static string ImProvStatus {
            get {
                return ResourceManager.GetString("ImProvStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Energization Confirmation.
        /// </summary>
        internal static string IndividualEnergizationConfirmation {
            get {
                return ResourceManager.GetString("IndividualEnergizationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Energization Setting.
        /// </summary>
        internal static string IndividualEnergizationSetting {
            get {
                return ResourceManager.GetString("IndividualEnergizationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantaneous Current (Phase A).
        /// </summary>
        internal static string InstantaneousCurrentPhaseA {
            get {
                return ResourceManager.GetString("InstantaneousCurrentPhaseA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantaneous Current (Phase B).
        /// </summary>
        internal static string InstantaneousCurrentPhaseB {
            get {
                return ResourceManager.GetString("InstantaneousCurrentPhaseB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantaneous Current (Phase C).
        /// </summary>
        internal static string InstantaneousCurrentPhaseC {
            get {
                return ResourceManager.GetString("InstantaneousCurrentPhaseC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantaneous Power Factor.
        /// </summary>
        internal static string InstantaneousPowerFactor {
            get {
                return ResourceManager.GetString("InstantaneousPowerFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantaneous Profile Data.
        /// </summary>
        internal static string InstantaneousProfileData {
            get {
                return ResourceManager.GetString("InstantaneousProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantaneous Voltage (Phase A).
        /// </summary>
        internal static string InstantaneousVoltagePhaseA {
            get {
                return ResourceManager.GetString("InstantaneousVoltagePhaseA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantaneous Voltage (Phase B).
        /// </summary>
        internal static string InstantaneousVoltagePhaseB {
            get {
                return ResourceManager.GetString("InstantaneousVoltagePhaseB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantaneous Voltage (Phase C).
        /// </summary>
        internal static string InstantaneousVoltagePhaseC {
            get {
                return ResourceManager.GetString("InstantaneousVoltagePhaseC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Function.
        /// </summary>
        internal static string InstrumentFunction {
            get {
                return ResourceManager.GetString("InstrumentFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Model Type.
        /// </summary>
        internal static string InstrumentModelType {
            get {
                return ResourceManager.GetString("InstrumentModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrogation Builder.
        /// </summary>
        internal static string InterrogationBuilder {
            get {
                return ResourceManager.GetString("InterrogationBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrogation Cleanup System Scripts.
        /// </summary>
        internal static string InterrogationCleanupSystemScripts {
            get {
                return ResourceManager.GetString("InterrogationCleanupSystemScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itron Alarm Indicator.
        /// </summary>
        internal static string ItronAlarmIndicator {
            get {
                return ResourceManager.GetString("ItronAlarmIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itron Alarm Register Monitor.
        /// </summary>
        internal static string ItronAlarmRegisterMonitor {
            get {
                return ResourceManager.GetString("ItronAlarmRegisterMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itron Event Code.
        /// </summary>
        internal static string ItronEventCode {
            get {
                return ResourceManager.GetString("ItronEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itron Event Detail.
        /// </summary>
        internal static string ItronEventDetail {
            get {
                return ResourceManager.GetString("ItronEventDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itron Event Log.
        /// </summary>
        internal static string ItronEventLog {
            get {
                return ResourceManager.GetString("ItronEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J.
        /// </summary>
        internal static string Joule {
            get {
                return ResourceManager.GetString("Joule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J/h.
        /// </summary>
        internal static string JoulePerHour {
            get {
                return ResourceManager.GetString("JoulePerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        internal static string KiloGram {
            get {
                return ResourceManager.GetString("KiloGram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Average Current (Phase A).
        /// </summary>
        internal static string LastAverageIPhaseA {
            get {
                return ResourceManager.GetString("LastAverageIPhaseA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Average Current (Phase B).
        /// </summary>
        internal static string LastAverageIPhaseB {
            get {
                return ResourceManager.GetString("LastAverageIPhaseB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Average Current (Phase C).
        /// </summary>
        internal static string LastAverageIPhaseC {
            get {
                return ResourceManager.GetString("LastAverageIPhaseC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Average Power Factor.
        /// </summary>
        internal static string LastAveragePF {
            get {
                return ResourceManager.GetString("LastAveragePF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Average Voltage (Phase A).
        /// </summary>
        internal static string LastAverageVPhaseA {
            get {
                return ResourceManager.GetString("LastAverageVPhaseA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Average Voltage (Phase B).
        /// </summary>
        internal static string LastAverageVPhaseB {
            get {
                return ResourceManager.GetString("LastAverageVPhaseB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Average Voltage (Phase C).
        /// </summary>
        internal static string LastAverageVPhaseC {
            get {
                return ResourceManager.GetString("LastAverageVPhaseC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Battery Reading.
        /// </summary>
        internal static string LastBatteryReading {
            get {
                return ResourceManager.GetString("LastBatteryReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Sync Expected Frequency.
        /// </summary>
        internal static string LineSyncExpectedFrequency {
            get {
                return ResourceManager.GetString("LineSyncExpectedFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l.
        /// </summary>
        internal static string Litre {
            get {
                return ResourceManager.GetString("Litre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Control Basic Settings.
        /// </summary>
        internal static string LoadControlBasicSettings {
            get {
                return ResourceManager.GetString("LoadControlBasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Control Confirmation.
        /// </summary>
        internal static string LoadControlConfirmation {
            get {
                return ResourceManager.GetString("LoadControlConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Control Operation Value.
        /// </summary>
        internal static string LoadControlOperationValue {
            get {
                return ResourceManager.GetString("LoadControlOperationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Control Temporary Settings.
        /// </summary>
        internal static string LoadControlTemporarySettings {
            get {
                return ResourceManager.GetString("LoadControlTemporarySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Limit Reserve.
        /// </summary>
        internal static string LoadLimitReserve {
            get {
                return ResourceManager.GetString("LoadLimitReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Side Voltage.
        /// </summary>
        internal static string LoadSideVoltage {
            get {
                return ResourceManager.GetString("LoadSideVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number of Authentication Errors Before Lockout.
        /// </summary>
        internal static string LockoutCount {
            get {
                return ResourceManager.GetString("LockoutCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout Time.
        /// </summary>
        internal static string LockoutTime {
            get {
                return ResourceManager.GetString("LockoutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Profile Set 1.
        /// </summary>
        internal static string LPSet1 {
            get {
                return ResourceManager.GetString("LPSet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Profile Set 1 Counter.
        /// </summary>
        internal static string LPSet1Counter {
            get {
                return ResourceManager.GetString("LPSet1Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Profile Set 2.
        /// </summary>
        internal static string LPSet2 {
            get {
                return ResourceManager.GetString("LPSet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Profile Set 2 Counter.
        /// </summary>
        internal static string LPSet2Counter {
            get {
                return ResourceManager.GetString("LPSet2Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Reconnect Push Setup.
        /// </summary>
        internal static string ManualReconnectPushSetup {
            get {
                return ResourceManager.GetString("ManualReconnectPushSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Condition Confirmation.
        /// </summary>
        internal static string MeterConditionConfirmation {
            get {
                return ResourceManager.GetString("MeterConditionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Reading of the Current Value.
        /// </summary>
        internal static string MeterReadingOfCurrentValue {
            get {
                return ResourceManager.GetString("MeterReadingOfCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Specifications.
        /// </summary>
        internal static string MeterSpecifications {
            get {
                return ResourceManager.GetString("MeterSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Time Synch Delta.
        /// </summary>
        internal static string MinimumTimeSynchDelta {
            get {
                return ResourceManager.GetString("MinimumTimeSynchDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multicast Server ApTitles.
        /// </summary>
        internal static string MulticastServerApTitles {
            get {
                return ResourceManager.GetString("MulticastServerApTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multicast Server Aptitles (No Config).
        /// </summary>
        internal static string MulticastServerApTitlesNoConfig {
            get {
                return ResourceManager.GetString("MulticastServerApTitlesNoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplying Factor.
        /// </summary>
        internal static string MultiplyingFactor {
            get {
                return ResourceManager.GetString("MultiplyingFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplying Factor Method.
        /// </summary>
        internal static string MultiplyingFactorMethod {
            get {
                return ResourceManager.GetString("MultiplyingFactorMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-stage Energization Setting.
        /// </summary>
        internal static string MultiStageEnergizationSetting {
            get {
                return ResourceManager.GetString("MultiStageEnergizationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Activity Suspension Duration.
        /// </summary>
        internal static string NetworkActivitySuspensionDuration {
            get {
                return ResourceManager.GetString("NetworkActivitySuspensionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Activity Suspension Monitor.
        /// </summary>
        internal static string NetworkActivitySuspensionMonitor {
            get {
                return ResourceManager.GetString("NetworkActivitySuspensionMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Activity Suspension Scripts.
        /// </summary>
        internal static string NetworkActivitySuspensionScripts {
            get {
                return ResourceManager.GetString("NetworkActivitySuspensionScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Statistics List.
        /// </summary>
        internal static string NetworkStatisticsList {
            get {
                return ResourceManager.GetString("NetworkStatisticsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetworkTimeSyncScripts.
        /// </summary>
        internal static string NetworkTimeSyncScripts {
            get {
                return ResourceManager.GetString("NetworkTimeSyncScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string Newton {
            get {
                return ResourceManager.GetString("Newton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nm.
        /// </summary>
        internal static string NewtonMeter {
            get {
                return ResourceManager.GetString("NewtonMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: Admin Status.
        /// </summary>
        internal static string NGCAdminStatus {
            get {
                return ResourceManager.GetString("NGCAdminStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC Debug: Description.
        /// </summary>
        internal static string NGCDebugDescription {
            get {
                return ResourceManager.GetString("NGCDebugDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC Debug: Detailed Metrics.
        /// </summary>
        internal static string NGCDebugDetailedMetrics {
            get {
                return ResourceManager.GetString("NGCDebugDetailedMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC Debug: Interface Metrics.
        /// </summary>
        internal static string NGCDebugInterfaceMetrics {
            get {
                return ResourceManager.GetString("NGCDebugInterfaceMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC Debug: NAN Driver.
        /// </summary>
        internal static string NGCDebugNANDriver {
            get {
                return ResourceManager.GetString("NGCDebugNANDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC Debug: RPL Config.
        /// </summary>
        internal static string NGCDebugRPLConfig {
            get {
                return ResourceManager.GetString("NGCDebugRPLConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC Debug: RPL Instance.
        /// </summary>
        internal static string NGCDebugRPLInstance {
            get {
                return ResourceManager.GetString("NGCDebugRPLInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC Debug: RPL Statistics.
        /// </summary>
        internal static string NGCDebugRPLStatistics {
            get {
                return ResourceManager.GetString("NGCDebugRPLStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC Debug: RPL Warm Start.
        /// </summary>
        internal static string NGCDebugRPLWarmStart {
            get {
                return ResourceManager.GetString("NGCDebugRPLWarmStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC Debug: UDP Metrics.
        /// </summary>
        internal static string NGCDebugUDPMetrics {
            get {
                return ResourceManager.GetString("NGCDebugUDPMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: In Broadcast Packets.
        /// </summary>
        internal static string NGCInBroadcastPackets {
            get {
                return ResourceManager.GetString("NGCInBroadcastPackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: In Discards.
        /// </summary>
        internal static string NGCInDiscards {
            get {
                return ResourceManager.GetString("NGCInDiscards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: In Errors.
        /// </summary>
        internal static string NGCInErrors {
            get {
                return ResourceManager.GetString("NGCInErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: In Multicast Packets.
        /// </summary>
        internal static string NGCInMulticastPackets {
            get {
                return ResourceManager.GetString("NGCInMulticastPackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: In Octets.
        /// </summary>
        internal static string NGCInOctets {
            get {
                return ResourceManager.GetString("NGCInOctets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: In Speed.
        /// </summary>
        internal static string NGCInSpeed {
            get {
                return ResourceManager.GetString("NGCInSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: In UDPv6 Datagrams.
        /// </summary>
        internal static string NGCInUDPv6Datagrams {
            get {
                return ResourceManager.GetString("NGCInUDPv6Datagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: In UDPv6 Errors.
        /// </summary>
        internal static string NGCInUDPv6Errors {
            get {
                return ResourceManager.GetString("NGCInUDPv6Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: In UDPv6 No Port.
        /// </summary>
        internal static string NGCInUDPv6NoPort {
            get {
                return ResourceManager.GetString("NGCInUDPv6NoPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: In Unicast Packets.
        /// </summary>
        internal static string NGCInUnicastPackets {
            get {
                return ResourceManager.GetString("NGCInUnicastPackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: In Unknown Protocol Packets.
        /// </summary>
        internal static string NGCInUnknownProtocolPackets {
            get {
                return ResourceManager.GetString("NGCInUnknownProtocolPackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: MTU Size.
        /// </summary>
        internal static string NGCMTUSize {
            get {
                return ResourceManager.GetString("NGCMTUSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: Out Broadcast Packets.
        /// </summary>
        internal static string NGCOutBroadcastPackets {
            get {
                return ResourceManager.GetString("NGCOutBroadcastPackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: Out Discards.
        /// </summary>
        internal static string NGCOutDiscards {
            get {
                return ResourceManager.GetString("NGCOutDiscards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: Out Errors.
        /// </summary>
        internal static string NGCOutErrors {
            get {
                return ResourceManager.GetString("NGCOutErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: Out Multicast Packets.
        /// </summary>
        internal static string NGCOutMulticastPackets {
            get {
                return ResourceManager.GetString("NGCOutMulticastPackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: Out Octets.
        /// </summary>
        internal static string NGCOutOctets {
            get {
                return ResourceManager.GetString("NGCOutOctets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: Output Status.
        /// </summary>
        internal static string NGCOutputStatus {
            get {
                return ResourceManager.GetString("NGCOutputStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: Out Queue Length.
        /// </summary>
        internal static string NGCOutQueueLength {
            get {
                return ResourceManager.GetString("NGCOutQueueLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: Out Speed.
        /// </summary>
        internal static string NGCOutSpeed {
            get {
                return ResourceManager.GetString("NGCOutSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: Out UDPv6 Datagrams.
        /// </summary>
        internal static string NGCOutUDPv6Datagrams {
            get {
                return ResourceManager.GetString("NGCOutUDPv6Datagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: Out Unicast Packets.
        /// </summary>
        internal static string NGCOutUnicastPackets {
            get {
                return ResourceManager.GetString("NGCOutUnicastPackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC: Physical Address (MAC).
        /// </summary>
        internal static string NGCPhysicalAddressMAC {
            get {
                return ResourceManager.GetString("NGCPhysicalAddressMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Best Parents List.
        /// </summary>
        internal static string NGCRPLBestParentsList {
            get {
                return ResourceManager.GetString("NGCRPLBestParentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: DAO Ack Messages Received.
        /// </summary>
        internal static string NGCRPLDAOAckMessagesReceived {
            get {
                return ResourceManager.GetString("NGCRPLDAOAckMessagesReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: DAO Ack Messages Transmitted.
        /// </summary>
        internal static string NGCRPLDAOAckMessagesTransmitted {
            get {
                return ResourceManager.GetString("NGCRPLDAOAckMessagesTransmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: DAO Messages Received.
        /// </summary>
        internal static string NGCRPLDAOMessagesReceived {
            get {
                return ResourceManager.GetString("NGCRPLDAOMessagesReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: DAO Messages Transmitted.
        /// </summary>
        internal static string NGCRPLDAOMessagesTransmitted {
            get {
                return ResourceManager.GetString("NGCRPLDAOMessagesTransmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: DIO Messages Received.
        /// </summary>
        internal static string NGCRPLDIOMessagesReceived {
            get {
                return ResourceManager.GetString("NGCRPLDIOMessagesReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: DIO Messages Transmitted.
        /// </summary>
        internal static string NGCRPLDIOMessagesTransmitted {
            get {
                return ResourceManager.GetString("NGCRPLDIOMessagesTransmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: DIS Messages Received.
        /// </summary>
        internal static string NGCRPLDISMessagesReceived {
            get {
                return ResourceManager.GetString("NGCRPLDISMessagesReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: DIS Messages Transmitted.
        /// </summary>
        internal static string NGCRPLDISMessagesTransmitted {
            get {
                return ResourceManager.GetString("NGCRPLDISMessagesTransmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: DoDag ID.
        /// </summary>
        internal static string NGCRPLDoDagID {
            get {
                return ResourceManager.GetString("NGCRPLDoDagID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: DoDag Last Changed.
        /// </summary>
        internal static string NGCRPLDoDagLastChanged {
            get {
                return ResourceManager.GetString("NGCRPLDoDagLastChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: DoDag Size.
        /// </summary>
        internal static string NGCRPLDoDagSize {
            get {
                return ResourceManager.GetString("NGCRPLDoDagSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: DoDag Version.
        /// </summary>
        internal static string NGCRPLDoDagVersion {
            get {
                return ResourceManager.GetString("NGCRPLDoDagVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Downward Directed Messages Received.
        /// </summary>
        internal static string NGCRPLDownwardDirectedMessagesReceived {
            get {
                return ResourceManager.GetString("NGCRPLDownwardDirectedMessagesReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Downward Directed Messages Transmitted.
        /// </summary>
        internal static string NGCRPLDownwardDirectedMessagesTransmitted {
            get {
                return ResourceManager.GetString("NGCRPLDownwardDirectedMessagesTransmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Global ETT.
        /// </summary>
        internal static string NGCRPLGlobalETT {
            get {
                return ResourceManager.GetString("NGCRPLGlobalETT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Global LQL.
        /// </summary>
        internal static string NGCRPLGlobalLQL {
            get {
                return ResourceManager.GetString("NGCRPLGlobalLQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Instance ID.
        /// </summary>
        internal static string NGCRPLInstanceID {
            get {
                return ResourceManager.GetString("NGCRPLInstanceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: IPv6 Address.
        /// </summary>
        internal static string NGCRPLIPv6Address {
            get {
                return ResourceManager.GetString("NGCRPLIPv6Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Number of Best Parents.
        /// </summary>
        internal static string NGCRPLNumberOfBestParents {
            get {
                return ResourceManager.GetString("NGCRPLNumberOfBestParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Number of Globally Repaired Messages.
        /// </summary>
        internal static string NGCRPLNumberOfGloballyRepairedMessages {
            get {
                return ResourceManager.GetString("NGCRPLNumberOfGloballyRepairedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Number of Locally Repaired Messages.
        /// </summary>
        internal static string NGCRPLNumberOfLocallyRepairedMessages {
            get {
                return ResourceManager.GetString("NGCRPLNumberOfLocallyRepairedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Number of Malformed Messages.
        /// </summary>
        internal static string NGCRPLNumberOfMalformedMessages {
            get {
                return ResourceManager.GetString("NGCRPLNumberOfMalformedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Number of Migrations.
        /// </summary>
        internal static string NGCRPLNumberOfMigrations {
            get {
                return ResourceManager.GetString("NGCRPLNumberOfMigrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Number of Neighbors.
        /// </summary>
        internal static string NGCRPLNumberOfNeighbors {
            get {
                return ResourceManager.GetString("NGCRPLNumberOfNeighbors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Number of PANs.
        /// </summary>
        internal static string NGCRPLNumberOfPANs {
            get {
                return ResourceManager.GetString("NGCRPLNumberOfPANs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Number of Parents.
        /// </summary>
        internal static string NGCRPLNumberOfParents {
            get {
                return ResourceManager.GetString("NGCRPLNumberOfParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: PAN ID.
        /// </summary>
        internal static string NGCRPLPANID {
            get {
                return ResourceManager.GetString("NGCRPLPANID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Rank.
        /// </summary>
        internal static string NGCRPLRank {
            get {
                return ResourceManager.GetString("NGCRPLRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Upward Directed Messages Received.
        /// </summary>
        internal static string NGCRPLUpwardDirectedMessagesReceived {
            get {
                return ResourceManager.GetString("NGCRPLUpwardDirectedMessagesReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGC RPL: Upward Directed Messages Transmitted.
        /// </summary>
        internal static string NGCRPLUpwardDirectedMessagesTransmitted {
            get {
                return ResourceManager.GetString("NGCRPLUpwardDirectedMessagesTransmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Configuration.
        /// </summary>
        internal static string NoConfiguration {
            get {
                return ResourceManager.GetString("NoConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Manual Disconnect, Remote Connect, No Local Connect.
        /// </summary>
        internal static string NoManualDisconnectRemoteReconnectManualReconnectNoLocalReconnect {
            get {
                return ResourceManager.GetString("NoManualDisconnectRemoteReconnectManualReconnectNoLocalReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Manual Disconnect, Remote Connect to Ready, Local Connect.
        /// </summary>
        internal static string NoManualDisconnectRemoteReconnectToReadyManualReconnectLocalReconnect {
            get {
                return ResourceManager.GetString("NoManualDisconnectRemoteReconnectToReadyManualReconnectLocalReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Manual Disconnect, Remote Connect to Ready, No Local Connect.
        /// </summary>
        internal static string NoManualDisconnectRemoteReconnectToReadyManualReconnectNoLocalReconnect {
            get {
                return ResourceManager.GetString("NoManualDisconnectRemoteReconnectToReadyManualReconnectNoLocalReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Billing Daily Self Read Data.
        /// </summary>
        internal static string NonBillingDailySelfReadData {
            get {
                return ResourceManager.GetString("NonBillingDailySelfReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Billing Self Read Data.
        /// </summary>
        internal static string NonBillingSelfReadData {
            get {
                return ResourceManager.GetString("NonBillingSelfReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Specified.
        /// </summary>
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Instrument Digits.
        /// </summary>
        internal static string NumberOfIntrumentDigits {
            get {
                return ResourceManager.GetString("NumberOfIntrumentDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Switching Operations.
        /// </summary>
        internal static string NumberOfSwitchingOperations {
            get {
                return ResourceManager.GetString("NumberOfSwitchingOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ω.
        /// </summary>
        internal static string Ohm {
            get {
                return ResourceManager.GetString("Ohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Display Values.
        /// </summary>
        internal static string OtherDisplayValues {
            get {
                return ResourceManager.GetString("OtherDisplayValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pa.
        /// </summary>
        internal static string Pascal {
            get {
                return ResourceManager.GetString("Pascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Wire System Type.
        /// </summary>
        internal static string PhaseWireSystemType {
            get {
                return ResourceManager.GetString("PhaseWireSystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC Firmware Version.
        /// </summary>
        internal static string PICFirmwareVersion {
            get {
                return ResourceManager.GetString("PICFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Destination Override.
        /// </summary>
        internal static string PushDestinationOverride {
            get {
                return ResourceManager.GetString("PushDestinationOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range For Registration Attempts.
        /// </summary>
        internal static string RangeForRegistrationAttempts {
            get {
                return ResourceManager.GetString("RangeForRegistrationAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated Current.
        /// </summary>
        internal static string RatedCurrent {
            get {
                return ResourceManager.GetString("RatedCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated Voltage.
        /// </summary>
        internal static string RatedVoltage {
            get {
                return ResourceManager.GetString("RatedVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconfigure Result.
        /// </summary>
        internal static string ReconfigureResult {
            get {
                return ResourceManager.GetString("ReconfigureResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Scalar Data.
        /// </summary>
        internal static string RegisterScalarData {
            get {
                return ResourceManager.GetString("RegisterScalarData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Push Setup.
        /// </summary>
        internal static string RegistrationPushSetup {
            get {
                return ResourceManager.GetString("RegistrationPushSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrations in Use.
        /// </summary>
        internal static string RegistrationsInUse {
            get {
                return ResourceManager.GetString("RegistrationsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Status.
        /// </summary>
        internal static string RegistrationStatus {
            get {
                return ResourceManager.GetString("RegistrationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Connect/Disconnect Script.
        /// </summary>
        internal static string RemoteConnectDiscconectScript {
            get {
                return ResourceManager.GetString("RemoteConnectDiscconectScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ωm^2/m.
        /// </summary>
        internal static string Resistivity {
            get {
                return ResourceManager.GetString("Resistivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Log Files.
        /// </summary>
        internal static string RetrieveLogFiles {
            get {
                return ResourceManager.GetString("RetrieveLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Setup.
        /// </summary>
        internal static string SecuritySetup {
            get {
                return ResourceManager.GetString("SecuritySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Setup (Encrypt and Authenticate).
        /// </summary>
        internal static string SecuritySetupEncryptAndAuthenticate {
            get {
                return ResourceManager.GetString("SecuritySetupEncryptAndAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Read Scripts.
        /// </summary>
        internal static string SelfReadScripts {
            get {
                return ResourceManager.GetString("SelfReadScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Read Single Action Schedule.
        /// </summary>
        internal static string SelfReadSingleActionSchedule {
            get {
                return ResourceManager.GetString("SelfReadSingleActionSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching Class.
        /// </summary>
        internal static string SwitchingClass {
            get {
                return ResourceManager.GetString("SwitchingClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching Condition Confirmation.
        /// </summary>
        internal static string SwitchingConditionConfirmation {
            get {
                return ResourceManager.GetString("SwitchingConditionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching Operation History Record Number.
        /// </summary>
        internal static string SwitchingOperationHistoryRecordNumber {
            get {
                return ResourceManager.GetString("SwitchingOperationHistoryRecordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Operation History.
        /// </summary>
        internal static string SwitchOperationHistory {
            get {
                return ResourceManager.GetString("SwitchOperationHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string Tesla {
            get {
                return ResourceManager.GetString("Tesla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 min Average Current Phase A.
        /// </summary>
        internal static string ThirtyMinAverageCurrentPhaseA {
            get {
                return ResourceManager.GetString("ThirtyMinAverageCurrentPhaseA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 min Average Current Phase B.
        /// </summary>
        internal static string ThirtyMinAverageCurrentPhaseB {
            get {
                return ResourceManager.GetString("ThirtyMinAverageCurrentPhaseB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 min Average Current Phase C.
        /// </summary>
        internal static string ThirtyMinAverageCurrentPhaseC {
            get {
                return ResourceManager.GetString("ThirtyMinAverageCurrentPhaseC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 min Average Voltage Phase A.
        /// </summary>
        internal static string ThirtyMinAverageVoltagePhaseA {
            get {
                return ResourceManager.GetString("ThirtyMinAverageVoltagePhaseA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 min Average Voltage Phase B.
        /// </summary>
        internal static string ThirtyMinAverageVoltagePhaseB {
            get {
                return ResourceManager.GetString("ThirtyMinAverageVoltagePhaseB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 min Average Voltage Phase C.
        /// </summary>
        internal static string ThirtyMinAverageVoltagePhaseC {
            get {
                return ResourceManager.GetString("ThirtyMinAverageVoltagePhaseC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Until Registration.
        /// </summary>
        internal static string TimeUntilRegistration {
            get {
                return ResourceManager.GetString("TimeUntilRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Outage Count.
        /// </summary>
        internal static string TotalOutageCount {
            get {
                return ResourceManager.GetString("TotalOutageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time On Battery.
        /// </summary>
        internal static string TotalTimeOnBattery {
            get {
                return ResourceManager.GetString("TotalTimeOnBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformer Ratio (denominator).
        /// </summary>
        internal static string TransformerRatioDenominator {
            get {
                return ResourceManager.GetString("TransformerRatioDenominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformer Ratio (numerator).
        /// </summary>
        internal static string TransformerRatioNumerator {
            get {
                return ResourceManager.GetString("TransformerRatioNumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VA.
        /// </summary>
        internal static string VA {
            get {
                return ResourceManager.GetString("VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAh.
        /// </summary>
        internal static string VAh {
            get {
                return ResourceManager.GetString("VAh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAh d.
        /// </summary>
        internal static string VAhDelivered {
            get {
                return ResourceManager.GetString("VAhDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAh r.
        /// </summary>
        internal static string VAhReceived {
            get {
                return ResourceManager.GetString("VAhReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var.
        /// </summary>
        internal static string var {
            get {
                return ResourceManager.GetString("var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varh.
        /// </summary>
        internal static string varh {
            get {
                return ResourceManager.GetString("varh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varh d.
        /// </summary>
        internal static string varhDelivered {
            get {
                return ResourceManager.GetString("varhDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varh d (Phase A).
        /// </summary>
        internal static string varhDeliveredPhaseA {
            get {
                return ResourceManager.GetString("varhDeliveredPhaseA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varh d (Phase B).
        /// </summary>
        internal static string varhDeliveredPhaseB {
            get {
                return ResourceManager.GetString("varhDeliveredPhaseB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varh d (Phase C).
        /// </summary>
        internal static string varhDeliveredPhaseC {
            get {
                return ResourceManager.GetString("varhDeliveredPhaseC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varh r.
        /// </summary>
        internal static string varhReceived {
            get {
                return ResourceManager.GetString("varhReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Client Association.
        /// </summary>
        internal static string VerificationClientAssociation {
            get {
                return ResourceManager.GetString("VerificationClientAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string Volt {
            get {
                return ResourceManager.GetString("Volt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V/m.
        /// </summary>
        internal static string VoltPerMeter {
            get {
                return ResourceManager.GetString("VoltPerMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage Transformer Ratio (denominator).
        /// </summary>
        internal static string VTRatioDenominator {
            get {
                return ResourceManager.GetString("VTRatioDenominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage Transformer Ratio (numerator).
        /// </summary>
        internal static string VTRatioNumerator {
            get {
                return ResourceManager.GetString("VTRatioNumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string Watt {
            get {
                return ResourceManager.GetString("Watt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W d.
        /// </summary>
        internal static string WDelivered {
            get {
                return ResourceManager.GetString("WDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wb.
        /// </summary>
        internal static string Weber {
            get {
                return ResourceManager.GetString("Weber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wh.
        /// </summary>
        internal static string Wh {
            get {
                return ResourceManager.GetString("Wh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wh d.
        /// </summary>
        internal static string WhDelivered {
            get {
                return ResourceManager.GetString("WhDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wh d (Phase A).
        /// </summary>
        internal static string WhDeliveredPhaseA {
            get {
                return ResourceManager.GetString("WhDeliveredPhaseA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wh d (Phase B).
        /// </summary>
        internal static string WhDeliveredPhaseB {
            get {
                return ResourceManager.GetString("WhDeliveredPhaseB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wh d (Phase C).
        /// </summary>
        internal static string WhDeliveredPhaseC {
            get {
                return ResourceManager.GetString("WhDeliveredPhaseC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wh r.
        /// </summary>
        internal static string WhReceived {
            get {
                return ResourceManager.GetString("WhReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wh r (Phase A).
        /// </summary>
        internal static string WhReceivedPhaseA {
            get {
                return ResourceManager.GetString("WhReceivedPhaseA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wh r (Phase B).
        /// </summary>
        internal static string WhReceivedPhaseB {
            get {
                return ResourceManager.GetString("WhReceivedPhaseB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wh r (Phase C).
        /// </summary>
        internal static string WhReceivedPhaseC {
            get {
                return ResourceManager.GetString("WhReceivedPhaseC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W r.
        /// </summary>
        internal static string WReceived {
            get {
                return ResourceManager.GetString("WReceived", resourceCulture);
            }
        }
    }
}
