//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itron.Metering.CustomerValidation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itron.Metering.CustomerValidation.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Poly Meter.
        /// </summary>
        internal static string AdvancedPolyMeter {
            get {
                return ResourceManager.GetString("AdvancedPolyMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All available radios in use..
        /// </summary>
        internal static string AllAvailableRadiosInUse {
            get {
                return ResourceManager.GetString("AllAvailableRadiosInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed ANSI C12.18 connection.
        /// </summary>
        internal static string AllowedANSIC1218Connection {
            get {
                return ResourceManager.GetString("AllowedANSIC1218Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANSI C12.18 Over ZigBee Enabled.
        /// </summary>
        internal static string ANSIC1218OverZigBeeEnabled {
            get {
                return ResourceManager.GetString("ANSIC1218OverZigBeeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read value.
        /// </summary>
        internal static string CannotReadValue {
            get {
                return ResourceManager.GetString("CannotReadValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Billing Data.
        /// </summary>
        internal static string ClearBillingData {
            get {
                return ResourceManager.GetString("ClearBillingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Demand Reset Count.
        /// </summary>
        internal static string ClearDemandResetCount {
            get {
                return ResourceManager.GetString("ClearDemandResetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Event Logs.
        /// </summary>
        internal static string ClearEventLogs {
            get {
                return ResourceManager.GetString("ClearEventLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear failed.
        /// </summary>
        internal static string ClearFailure {
            get {
                return ResourceManager.GetString("ClearFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Inversion Tampers.
        /// </summary>
        internal static string ClearInversionTampers {
            get {
                return ResourceManager.GetString("ClearInversionTampers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Power Outage Count.
        /// </summary>
        internal static string ClearPowerOutageCount {
            get {
                return ResourceManager.GetString("ClearPowerOutageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Programmed Count.
        /// </summary>
        internal static string ClearProgrammedCount {
            get {
                return ResourceManager.GetString("ClearProgrammedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Removal Tampers.
        /// </summary>
        internal static string ClearRemovalTampers {
            get {
                return ResourceManager.GetString("ClearRemovalTampers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear SiteScan Diagnostic Counts.
        /// </summary>
        internal static string ClearSiteScanDiagnosticCounts {
            get {
                return ResourceManager.GetString("ClearSiteScanDiagnosticCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear succeeded.
        /// </summary>
        internal static string ClearSuccess {
            get {
                return ResourceManager.GetString("ClearSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count cleared.
        /// </summary>
        internal static string CountCleared {
            get {
                return ResourceManager.GetString("CountCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count not cleared.
        /// </summary>
        internal static string CountNotCleared {
            get {
                return ResourceManager.GetString("CountNotCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Last Programmed.
        /// </summary>
        internal static string DateLastProgrammed {
            get {
                return ResourceManager.GetString("DateLastProgrammed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Last Demand Reset.
        /// </summary>
        internal static string DateOfLastDemandReset {
            get {
                return ResourceManager.GetString("DateOfLastDemandReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Last Outage.
        /// </summary>
        internal static string DateOfLastOutage {
            get {
                return ResourceManager.GetString("DateOfLastOutage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Last Test.
        /// </summary>
        internal static string DateOfLastTest {
            get {
                return ResourceManager.GetString("DateOfLastTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Reset Count.
        /// </summary>
        internal static string DemandResetCount {
            get {
                return ResourceManager.GetString("DemandResetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DES Key 1.
        /// </summary>
        internal static string DESKey1 {
            get {
                return ResourceManager.GetString("DESKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DES Key 2.
        /// </summary>
        internal static string DESKey2 {
            get {
                return ResourceManager.GetString("DESKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DES Key 3.
        /// </summary>
        internal static string DESKey3 {
            get {
                return ResourceManager.GetString("DESKey3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DES Key 4.
        /// </summary>
        internal static string DESKey4 {
            get {
                return ResourceManager.GetString("DESKey4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Error .
        /// </summary>
        internal static string DeviceError {
            get {
                return ResourceManager.GetString("DeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Errors.
        /// </summary>
        internal static string DeviceErrors {
            get {
                return ResourceManager.GetString("DeviceErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Time.
        /// </summary>
        internal static string DeviceTime {
            get {
                return ResourceManager.GetString("DeviceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Firmware Version.
        /// </summary>
        internal static string DisplayFirmwareVersion {
            get {
                return ResourceManager.GetString("DisplayFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DST Enabled.
        /// </summary>
        internal static string DSTEnabled {
            get {
                return ResourceManager.GetString("DSTEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DST From Date .
        /// </summary>
        internal static string DSTFromDate {
            get {
                return ResourceManager.GetString("DSTFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DST To Date .
        /// </summary>
        internal static string DSTToDate {
            get {
                return ResourceManager.GetString("DSTToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Serial Number.
        /// </summary>
        internal static string ElectronicSerialNumber {
            get {
                return ResourceManager.GetString("ElectronicSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Blurts Enabled.
        /// </summary>
        internal static string EnhancedBlurtsEnabled {
            get {
                return ResourceManager.GetString("EnhancedBlurtsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Security Command Key 1.
        /// </summary>
        internal static string EnhancedSecurityCommandKey1 {
            get {
                return ResourceManager.GetString("EnhancedSecurityCommandKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Security Command Key 2.
        /// </summary>
        internal static string EnhancedSecurityCommandKey2 {
            get {
                return ResourceManager.GetString("EnhancedSecurityCommandKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Security Command Key 3.
        /// </summary>
        internal static string EnhancedSecurityCommandKey3 {
            get {
                return ResourceManager.GetString("EnhancedSecurityCommandKey3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Security Command Key 4.
        /// </summary>
        internal static string EnhancedSecurityCommandKey4 {
            get {
                return ResourceManager.GetString("EnhancedSecurityCommandKey4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Security Revocation Key 1.
        /// </summary>
        internal static string EnhancedSecurityRevocationKey1 {
            get {
                return ResourceManager.GetString("EnhancedSecurityRevocationKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Security Revocation Key 2.
        /// </summary>
        internal static string EnhancedSecurityRevocationKey2 {
            get {
                return ResourceManager.GetString("EnhancedSecurityRevocationKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error present.
        /// </summary>
        internal static string ErrorPresent {
            get {
                return ResourceManager.GetString("ErrorPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors Found.
        /// </summary>
        internal static string ErrorsFound {
            get {
                return ResourceManager.GetString("ErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Log Count.
        /// </summary>
        internal static string EventLogCount {
            get {
                return ResourceManager.GetString("EventLogCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared event(s) not in enabled log.
        /// </summary>
        internal static string EventNotFoundInEnabledLog {
            get {
                return ResourceManager.GetString("EventNotFoundInEnabledLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events cleared.
        /// </summary>
        internal static string EventsCleared {
            get {
                return ResourceManager.GetString("EventsCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event(s) found in disabled log.
        /// </summary>
        internal static string EventsFoundInDisabledLog {
            get {
                return ResourceManager.GetString("EventsFoundInDisabledLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events not cleared.
        /// </summary>
        internal static string EventsNotCleared {
            get {
                return ResourceManager.GetString("EventsNotCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Occurred.
        /// </summary>
        internal static string ExceptionOccurred {
            get {
                return ResourceManager.GetString("ExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  found.
        /// </summary>
        internal static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMT .
        /// </summary>
        internal static string GMT {
            get {
                return ResourceManager.GetString("GMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAN Channel.
        /// </summary>
        internal static string HANChannel {
            get {
                return ResourceManager.GetString("HANChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAN Joining Enabled.
        /// </summary>
        internal static string HANJoiningEnabled {
            get {
                return ResourceManager.GetString("HANJoiningEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAN Link Key.
        /// </summary>
        internal static string HANLinkKey {
            get {
                return ResourceManager.GetString("HANLinkKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAN MAC Address.
        /// </summary>
        internal static string HANMACAddress {
            get {
                return ResourceManager.GetString("HANMACAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAN Network Key.
        /// </summary>
        internal static string HANNetworkKey {
            get {
                return ResourceManager.GetString("HANNetworkKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAN Security Profile.
        /// </summary>
        internal static string HANSecurityProfile {
            get {
                return ResourceManager.GetString("HANSecurityProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Version.
        /// </summary>
        internal static string HardwareVersion {
            get {
                return ResourceManager.GetString("HardwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent with HAN setup.
        /// </summary>
        internal static string InconsistentWithHANSetup {
            get {
                return ResourceManager.GetString("InconsistentWithHANSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterPAN Mode.
        /// </summary>
        internal static string InterPANMode {
            get {
                return ResourceManager.GetString("InterPANMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid program file for verification.
        /// </summary>
        internal static string InvalidProgram {
            get {
                return ResourceManager.GetString("InvalidProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inversion Tamper Count.
        /// </summary>
        internal static string InversionTamperCount {
            get {
                return ResourceManager.GetString("InversionTamperCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is not consistent with program file.
        /// </summary>
        internal static string KeyNotConsistentWithProgram {
            get {
                return ResourceManager.GetString("KeyNotConsistentWithProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is not consistent with registry.
        /// </summary>
        internal static string KeyNotConsistentWithRegistry {
            get {
                return ResourceManager.GetString("KeyNotConsistentWithRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is not consistent with enhanced security key file.
        /// </summary>
        internal static string KeyNotConsistentWithSecurityFile {
            get {
                return ResourceManager.GetString("KeyNotConsistentWithSecurityFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Profile Running.
        /// </summary>
        internal static string LoadProfileRunning {
            get {
                return ResourceManager.GetString("LoadProfileRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Voltage Present.
        /// </summary>
        internal static string LoadVoltagePresent {
            get {
                return ResourceManager.GetString("LoadVoltagePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log disabled.
        /// </summary>
        internal static string LogDisabled {
            get {
                return ResourceManager.GetString("LogDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches active version.
        /// </summary>
        internal static string MatchesActiveVersion {
            get {
                return ResourceManager.GetString("MatchesActiveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        internal static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter ID.
        /// </summary>
        internal static string MeterID {
            get {
                return ResourceManager.GetString("MeterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter should be connected.
        /// </summary>
        internal static string MeterShouldBeConnected {
            get {
                return ResourceManager.GetString("MeterShouldBeConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter should be disconnected.
        /// </summary>
        internal static string MeterShouldBeDisconnected {
            get {
                return ResourceManager.GetString("MeterShouldBeDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter should have load voltage.
        /// </summary>
        internal static string MeterShouldHaveLoadVoltage {
            get {
                return ResourceManager.GetString("MeterShouldHaveLoadVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter should not have load voltage.
        /// </summary>
        internal static string MeterShouldNotHaveLoadVoltage {
            get {
                return ResourceManager.GetString("MeterShouldNotHaveLoadVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This meter type is not supported.
        /// </summary>
        internal static string MeterTypeNotSupported {
            get {
                return ResourceManager.GetString("MeterTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Value = .
        /// </summary>
        internal static string MeterValueEquals {
            get {
                return ResourceManager.GetString("MeterValueEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFG Serial Number.
        /// </summary>
        internal static string MFGSerialNumber {
            get {
                return ResourceManager.GetString("MFGSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes on Battery.
        /// </summary>
        internal static string MinutesOnBattery {
            get {
                return ResourceManager.GetString("MinutesOnBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch with active version.
        /// </summary>
        internal static string MismatchWithActiveVersion {
            get {
                return ResourceManager.GetString("MismatchWithActiveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file set as active for comparison.
        /// </summary>
        internal static string NoActiveFile {
            get {
                return ResourceManager.GetString("NoActiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Errors Found.
        /// </summary>
        internal static string NoErrorsFound {
            get {
                return ResourceManager.GetString("NoErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None present.
        /// </summary>
        internal static string NonePresent {
            get {
                return ResourceManager.GetString("NonePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No program file for verification.
        /// </summary>
        internal static string NoProgram {
            get {
                return ResourceManager.GetString("NoProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No radios available..
        /// </summary>
        internal static string NoRadiosAvailable {
            get {
                return ResourceManager.GetString("NoRadiosAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Display Items.
        /// </summary>
        internal static string NormalDisplayItems {
            get {
                return ResourceManager.GetString("NormalDisplayItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Kh.
        /// </summary>
        internal static string NormalKh {
            get {
                return ResourceManager.GetString("NormalKh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        internal static string OperationFailure {
            get {
                return ResourceManager.GetString("OperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation succeeded.
        /// </summary>
        internal static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        internal static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not consistent with program file.
        /// </summary>
        internal static string PasswordNotConsistentWithProgram {
            get {
                return ResourceManager.GetString("PasswordNotConsistentWithProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Outage Count.
        /// </summary>
        internal static string PowerOutageCount {
            get {
                return ResourceManager.GetString("PowerOutageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final .
        /// </summary>
        internal static string PrefixFinal {
            get {
                return ResourceManager.GetString("PrefixFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial .
        /// </summary>
        internal static string PrefixInitial {
            get {
                return ResourceManager.GetString("PrefixInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Optical Password.
        /// </summary>
        internal static string PrimaryOpticalPassword {
            get {
                return ResourceManager.GetString("PrimaryOpticalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistent with selected program file.
        /// </summary>
        internal static string ProgramMatch {
            get {
                return ResourceManager.GetString("ProgramMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmed Count.
        /// </summary>
        internal static string ProgrammedCount {
            get {
                return ResourceManager.GetString("ProgrammedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch with selected program file.
        /// </summary>
        internal static string ProgramMismatch {
            get {
                return ResourceManager.GetString("ProgramMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Validation Errors.
        /// </summary>
        internal static string ProgramValidationErrors {
            get {
                return ResourceManager.GetString("ProgramValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaternary Optical Password.
        /// </summary>
        internal static string QuaternaryOpticalPassword {
            get {
                return ResourceManager.GetString("QuaternaryOpticalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not allowed to reset Activity Status.
        /// </summary>
        internal static string ReasonActivityStatusPermissions {
            get {
                return ResourceManager.GetString("ReasonActivityStatusPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity status cannot be cleared on a sealed Canadian meter..
        /// </summary>
        internal static string ReasonActivityStatusSealedCanadian {
            get {
                return ResourceManager.GetString("ReasonActivityStatusSealedCanadian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not allowed to perform a Billing Register reset.
        /// </summary>
        internal static string ReasonBillingResetPermissions {
            get {
                return ResourceManager.GetString("ReasonBillingResetPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing cannot be cleared on a sealed Canadian meter..
        /// </summary>
        internal static string ReasonBillingResetSealedCanadian {
            get {
                return ResourceManager.GetString("ReasonBillingResetSealedCanadian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This meter does not support remote disconnect..
        /// </summary>
        internal static string ReasonDisconnectNotSupported {
            get {
                return ResourceManager.GetString("ReasonDisconnectNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Enhanced Security file must be specified to validate this key..
        /// </summary>
        internal static string ReasonEnhSecurtyFileRequired {
            get {
                return ResourceManager.GetString("ReasonEnhSecurtyFileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve device&apos;s HAN information.
        /// </summary>
        internal static string ReasonFailedToGetHANInfo {
            get {
                return ResourceManager.GetString("ReasonFailedToGetHANInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  invalid items found..
        /// </summary>
        internal static string ReasonInvalidItemsFound {
            get {
                return ResourceManager.GetString("ReasonInvalidItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid program file was selected..
        /// </summary>
        internal static string ReasonInvalidProgramFile {
            get {
                return ResourceManager.GetString("ReasonInvalidProgramFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Voltage not detected.
        /// </summary>
        internal static string ReasonLoadVoltageNotDetected {
            get {
                return ResourceManager.GetString("ReasonLoadVoltageNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Voltage present.
        /// </summary>
        internal static string ReasonLoadVoltagePresent {
            get {
                return ResourceManager.GetString("ReasonLoadVoltagePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Logon to device.
        /// </summary>
        internal static string ReasonLogonFailed {
            get {
                return ResourceManager.GetString("ReasonLogonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active firmware file..
        /// </summary>
        internal static string ReasonNoFirmwareFile {
            get {
                return ResourceManager.GetString("ReasonNoFirmwareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program file was not selected..
        /// </summary>
        internal static string ReasonNoProgramFile {
            get {
                return ResourceManager.GetString("ReasonNoProgramFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 invalid item found..
        /// </summary>
        internal static string ReasonOneInvalidItemFound {
            get {
                return ResourceManager.GetString("ReasonOneInvalidItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not supported.
        /// </summary>
        internal static string ReasonOperationNotSupported {
            get {
                return ResourceManager.GetString("ReasonOperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program file must be specified to validate this password..
        /// </summary>
        internal static string ReasonProgramFileNeededToValidate {
            get {
                return ResourceManager.GetString("ReasonProgramFileNeededToValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program file must be specified to validate this key..
        /// </summary>
        internal static string ReasonProgramFileNeededToValidateKey {
            get {
                return ResourceManager.GetString("ReasonProgramFileNeededToValidateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol error.
        /// </summary>
        internal static string ReasonProtocolError {
            get {
                return ResourceManager.GetString("ReasonProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote connect failed.
        /// </summary>
        internal static string ReasonRemoteConnectFailed {
            get {
                return ResourceManager.GetString("ReasonRemoteConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security error.
        /// </summary>
        internal static string ReasonSecurityError {
            get {
                return ResourceManager.GetString("ReasonSecurityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiteScan is not supported by this device.
        /// </summary>
        internal static string ReasonSiteScanNotSupported {
            get {
                return ResourceManager.GetString("ReasonSiteScanNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This test requires Register Firmware 2.005 or later.
        /// </summary>
        internal static string ReasonSP5OrLaterRequired {
            get {
                return ResourceManager.GetString("ReasonSP5OrLaterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not allowed to perform switch operations.
        /// </summary>
        internal static string ReasonSwitchOperationPermissions {
            get {
                return ResourceManager.GetString("ReasonSwitchOperationPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized procedure.
        /// </summary>
        internal static string ReasonUnrecognizedProcedure {
            get {
                return ResourceManager.GetString("ReasonUnrecognizedProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Firmware Version.
        /// </summary>
        internal static string RegisterFirmwareVersion {
            get {
                return ResourceManager.GetString("RegisterFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Connect.
        /// </summary>
        internal static string RemoteConnect {
            get {
                return ResourceManager.GetString("RemoteConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Disconnect.
        /// </summary>
        internal static string RemoteDisconnect {
            get {
                return ResourceManager.GetString("RemoteDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removal Tamper Count.
        /// </summary>
        internal static string RemovalTamperCount {
            get {
                return ResourceManager.GetString("RemovalTamperCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm Module Firmware Version.
        /// </summary>
        internal static string RFLANFirmwareVersion {
            get {
                return ResourceManager.GetString("RFLANFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm Module MAC Address.
        /// </summary>
        internal static string RFLANMACAddress {
            get {
                return ResourceManager.GetString("RFLANMACAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm Module synch level.
        /// </summary>
        internal static string RFLANSynchLevel {
            get {
                return ResourceManager.GetString("RFLANSynchLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Optical Password.
        /// </summary>
        internal static string SecondaryOpticalPassword {
            get {
                return ResourceManager.GetString("SecondaryOpticalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string Skipped {
            get {
                return ResourceManager.GetString("Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports ANSI C12.18 over ZigBee.
        /// </summary>
        internal static string SupportsANSIC1218OverZigBee {
            get {
                return ResourceManager.GetString("SupportsANSIC1218OverZigBee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tertiary Optical Password.
        /// </summary>
        internal static string TertiaryOpticalPassword {
            get {
                return ResourceManager.GetString("TertiaryOpticalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        internal static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOU Enabled.
        /// </summary>
        internal static string TOUEnabled {
            get {
                return ResourceManager.GetString("TOUEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed.
        /// </summary>
        internal static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZigBee Enabled.
        /// </summary>
        internal static string ZigBeeEnabled {
            get {
                return ResourceManager.GetString("ZigBeeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZigBee Firmware Version.
        /// </summary>
        internal static string ZigBeeFirmwareVersion {
            get {
                return ResourceManager.GetString("ZigBeeFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZigBee Private Profile Enabled.
        /// </summary>
        internal static string ZigBeePrivateProfileEnabled {
            get {
                return ResourceManager.GetString("ZigBeePrivateProfileEnabled", resourceCulture);
            }
        }
    }
}
