//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itron.Metering.Communications.DLMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DLMSCommStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DLMSCommStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itron.Metering.Communications.DLMS.DLMSCommStrings", typeof(DLMSCommStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Month.
        /// </summary>
        internal static string DayOfMonth {
            get {
                return ResourceManager.GetString("DayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Week.
        /// </summary>
        internal static string DayOfWeek {
            get {
                return ResourceManager.GetString("DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month when DST ends.
        /// </summary>
        internal static string DSTEndMonth {
            get {
                return ResourceManager.GetString("DSTEndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month when DST starts.
        /// </summary>
        internal static string DSTStartMonth {
            get {
                return ResourceManager.GetString("DSTStartMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18th.
        /// </summary>
        internal static string Eighteenth {
            get {
                return ResourceManager.GetString("Eighteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8th.
        /// </summary>
        internal static string Eighth {
            get {
                return ResourceManager.GetString("Eighth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11th.
        /// </summary>
        internal static string Eleventh {
            get {
                return ResourceManager.GetString("Eleventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Day.
        /// </summary>
        internal static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Day at [TIME].
        /// </summary>
        internal static string EveryDayAtTime {
            get {
                return ResourceManager.GetString("EveryDayAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15th.
        /// </summary>
        internal static string Fifteenth {
            get {
                return ResourceManager.GetString("Fifteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5th.
        /// </summary>
        internal static string Fifth {
            get {
                return ResourceManager.GetString("Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First [WEEKDAY] on or after the [DATE] of every month.
        /// </summary>
        internal static string FirstWeekdayAfterDateInEveryMonth {
            get {
                return ResourceManager.GetString("FirstWeekdayAfterDateInEveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First [WEEKDAY] on or after the [DATE] of every month at [TIME].
        /// </summary>
        internal static string FirstWeekdayAfterDateInEveryMonthWithTime {
            get {
                return ResourceManager.GetString("FirstWeekdayAfterDateInEveryMonthWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First [WEEKDAY] on or after the [DATE] of [MONTH].
        /// </summary>
        internal static string FirstWeekdayAfterDateInSpecificMonth {
            get {
                return ResourceManager.GetString("FirstWeekdayAfterDateInSpecificMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First [WEEKDAY] on or after the [DATE] of [MONTH] at [TIME].
        /// </summary>
        internal static string FirstWeekdayAfterDateInSpecificMonthWithTime {
            get {
                return ResourceManager.GetString("FirstWeekdayAfterDateInSpecificMonthWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14th.
        /// </summary>
        internal static string Fourteenth {
            get {
                return ResourceManager.GetString("Fourteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th.
        /// </summary>
        internal static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last day of every month in [YEAR].
        /// </summary>
        internal static string LasDayOfTheMonthInYear {
            get {
                return ResourceManager.GetString("LasDayOfTheMonthInYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last day of every month in [YEAR] at [TIME].
        /// </summary>
        internal static string LasDayOfTheMonthInYearWithTime {
            get {
                return ResourceManager.GetString("LasDayOfTheMonthInYearWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Day of the Month.
        /// </summary>
        internal static string LastDay {
            get {
                return ResourceManager.GetString("LastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last day of every month.
        /// </summary>
        internal static string LastDayOfTheMonth {
            get {
                return ResourceManager.GetString("LastDayOfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last day of every month at [TIME].
        /// </summary>
        internal static string LastDayOfTheMonthWithTime {
            get {
                return ResourceManager.GetString("LastDayOfTheMonthWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last [WEEKDAY] of every month.
        /// </summary>
        internal static string LastWeekdayOfTheMonth {
            get {
                return ResourceManager.GetString("LastWeekdayOfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last [WEEKDAY] of every month in [YEAR].
        /// </summary>
        internal static string LastWeekdayOfTheMonthInYear {
            get {
                return ResourceManager.GetString("LastWeekdayOfTheMonthInYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last [WEEKDAY] of every month in [YEAR] at [TIME].
        /// </summary>
        internal static string LastWeekdayOfTheMonthInYearWithTime {
            get {
                return ResourceManager.GetString("LastWeekdayOfTheMonthInYearWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last [WEEKDAY] of every month at [TIME].
        /// </summary>
        internal static string LastWeekdayOfTheMonthWithTime {
            get {
                return ResourceManager.GetString("LastWeekdayOfTheMonthWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19th.
        /// </summary>
        internal static string Nineteenth {
            get {
                return ResourceManager.GetString("Nineteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9th.
        /// </summary>
        internal static string Ninth {
            get {
                return ResourceManager.GetString("Ninth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Specified.
        /// </summary>
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second To Last Day of the Month.
        /// </summary>
        internal static string SecondToLastDay {
            get {
                return ResourceManager.GetString("SecondToLastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second to last day of every month.
        /// </summary>
        internal static string SecondToLastDayOfTheMonth {
            get {
                return ResourceManager.GetString("SecondToLastDayOfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second to last day of every month in [YEAR].
        /// </summary>
        internal static string SecondToLastDayOfTheMonthInYear {
            get {
                return ResourceManager.GetString("SecondToLastDayOfTheMonthInYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second to last day of every month in [YEAR] at [TIME].
        /// </summary>
        internal static string SecondToLastDayOfTheMonthInYearWithTime {
            get {
                return ResourceManager.GetString("SecondToLastDayOfTheMonthInYearWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second to last day of every month at [TIME].
        /// </summary>
        internal static string SecondToLastDayOfTheMonthWithTime {
            get {
                return ResourceManager.GetString("SecondToLastDayOfTheMonthWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17th.
        /// </summary>
        internal static string Seventeenth {
            get {
                return ResourceManager.GetString("Seventeenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7th.
        /// </summary>
        internal static string Seventh {
            get {
                return ResourceManager.GetString("Seventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16th.
        /// </summary>
        internal static string Sixteenth {
            get {
                return ResourceManager.GetString("Sixteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6th.
        /// </summary>
        internal static string Sixth {
            get {
                return ResourceManager.GetString("Sixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10th.
        /// </summary>
        internal static string Tenth {
            get {
                return ResourceManager.GetString("Tenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd.
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13th.
        /// </summary>
        internal static string Thirteenth {
            get {
                return ResourceManager.GetString("Thirteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30th.
        /// </summary>
        internal static string Thirtieth {
            get {
                return ResourceManager.GetString("Thirtieth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31st.
        /// </summary>
        internal static string Thirtyfirst {
            get {
                return ResourceManager.GetString("Thirtyfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12th.
        /// </summary>
        internal static string Twelfth {
            get {
                return ResourceManager.GetString("Twelfth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20th.
        /// </summary>
        internal static string Twentieth {
            get {
                return ResourceManager.GetString("Twentieth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28th.
        /// </summary>
        internal static string Twentyeighth {
            get {
                return ResourceManager.GetString("Twentyeighth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25th.
        /// </summary>
        internal static string Twentyfifth {
            get {
                return ResourceManager.GetString("Twentyfifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21st.
        /// </summary>
        internal static string Twentyfirst {
            get {
                return ResourceManager.GetString("Twentyfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24th.
        /// </summary>
        internal static string Twentyfourth {
            get {
                return ResourceManager.GetString("Twentyfourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29th.
        /// </summary>
        internal static string Twentyninth {
            get {
                return ResourceManager.GetString("Twentyninth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22nd.
        /// </summary>
        internal static string Twentysecond {
            get {
                return ResourceManager.GetString("Twentysecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27th.
        /// </summary>
        internal static string Twentyseventh {
            get {
                return ResourceManager.GetString("Twentyseventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26th.
        /// </summary>
        internal static string Twentysixth {
            get {
                return ResourceManager.GetString("Twentysixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23rd.
        /// </summary>
        internal static string Twentythird {
            get {
                return ResourceManager.GetString("Twentythird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
