//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itron.Metering.CustomerValidationTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itron.Metering.CustomerValidationTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type.
        /// </summary>
        internal static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Serial Number.
        /// </summary>
        internal static string ElectronicSerialNumber {
            get {
                return ResourceManager.GetString("ElectronicSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute command.  View details for more information.
        /// </summary>
        internal static string ERROR_COMMAND_EXECUTION {
            get {
                return ResourceManager.GetString("ERROR_COMMAND_EXECUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application can not be closed while tests are running..
        /// </summary>
        internal static string ErrorCantCloseApp {
            get {
                return ResourceManager.GetString("ErrorCantCloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open results file..
        /// </summary>
        internal static string ErrorCouldNotOpenResultsFile {
            get {
                return ResourceManager.GetString("ErrorCouldNotOpenResultsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving device identification.
        /// </summary>
        internal static string ErrorRetrievingDeviceIdentification {
            get {
                return ResourceManager.GetString("ErrorRetrievingDeviceIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors Found.
        /// </summary>
        internal static string ErrorsFound {
            get {
                return ResourceManager.GetString("ErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while opening the help file..
        /// </summary>
        internal static string ErrrorHelpFile {
            get {
                return ResourceManager.GetString("ErrrorHelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Spreadsheet|*.xls.
        /// </summary>
        internal static string ExcelFileFilter {
            get {
                return ResourceManager.GetString("ExcelFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: Exception occurred.
        /// </summary>
        internal static string FailedExceptionOccurred {
            get {
                return ResourceManager.GetString("FailedExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This meter type is not supported.
        /// </summary>
        internal static string MeterTypeNotSupported {
            get {
                return ResourceManager.GetString("MeterTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Errors Found.
        /// </summary>
        internal static string NoErrorsFound {
            get {
                return ResourceManager.GetString("NoErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenWay CENTRON.
        /// </summary>
        internal static string OpenWayCENTRON {
            get {
                return ResourceManager.GetString("OpenWayCENTRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenWay CENTRON Advanced Poly.
        /// </summary>
        internal static string OpenWayCENTRONAdvancedPoly {
            get {
                return ResourceManager.GetString("OpenWayCENTRONAdvancedPoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenWay CENTRON Basic Poly.
        /// </summary>
        internal static string OpenWayCENTRONBasicPoly {
            get {
                return ResourceManager.GetString("OpenWayCENTRONBasicPoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenWay Transparent Device.
        /// </summary>
        internal static string OpenWayTransparentDevice {
            get {
                return ResourceManager.GetString("OpenWayTransparentDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        internal static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe 1.
        /// </summary>
        internal static string Probe1 {
            get {
                return ResourceManager.GetString("Probe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe 2.
        /// </summary>
        internal static string Probe2 {
            get {
                return ResourceManager.GetString("Probe2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe 3.
        /// </summary>
        internal static string Probe3 {
            get {
                return ResourceManager.GetString("Probe3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe 4.
        /// </summary>
        internal static string Probe4 {
            get {
                return ResourceManager.GetString("Probe4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Used.
        /// </summary>
        internal static string ProgramUsed {
            get {
                return ResourceManager.GetString("ProgramUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred: .
        /// </summary>
        internal static string ReasonExceptionOccurred {
            get {
                return ResourceManager.GetString("ReasonExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Result File|*.xml.
        /// </summary>
        internal static string ResultsFileFilter {
            get {
                return ResourceManager.GetString("ResultsFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select export file location.
        /// </summary>
        internal static string SelectExportFileLocation {
            get {
                return ResourceManager.GetString("SelectExportFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select results file.
        /// </summary>
        internal static string SelectResultsFile {
            get {
                return ResourceManager.GetString("SelectResultsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string Skipped {
            get {
                return ResourceManager.GetString("Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Version.
        /// </summary>
        internal static string SoftwareVersion {
            get {
                return ResourceManager.GetString("SoftwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string StatusComplete {
            get {
                return ResourceManager.GetString("StatusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving device information....
        /// </summary>
        internal static string StatusRetrievingDeviceInfo {
            get {
                return ResourceManager.GetString("StatusRetrievingDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Test: .
        /// </summary>
        internal static string StatusRunningTest {
            get {
                return ResourceManager.GetString("StatusRunningTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving results....
        /// </summary>
        internal static string StatusSavingResults {
            get {
                return ResourceManager.GetString("StatusSavingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Date.
        /// </summary>
        internal static string TestDate {
            get {
                return ResourceManager.GetString("TestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested: .
        /// </summary>
        internal static string Tested {
            get {
                return ResourceManager.GetString("Tested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Information.
        /// </summary>
        internal static string TestInformation {
            get {
                return ResourceManager.GetString("TestInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Validation Results.
        /// </summary>
        internal static string ValidationResults {
            get {
                return ResourceManager.GetString("ValidationResults", resourceCulture);
            }
        }
    }
}
